[package]
name = "jirs-client"
version = "0.1.0"
authors = ["Adrian Wozniak <adrian.wozniak@ita-prog.pl>"]
edition = "2018"
description = "JIRS (Simplified JIRA in Rust) WASM client"
repository = "https://gitlab.com/adrian.wozniak/jirs"
license = "MPL-2.0"
#license-file = "../LICENSE"

[lib]
crate-type = ["cdylib", "rlib"]
name = "jirs_client"
path = "./src/lib.rs"

[dependencies]
jirs-data = { path = "../jirs-data" }
seed = { version = "*" }
serde = "*"
serde_json = "*"
chrono = { version = "*", features = [ "serde" ] }
uuid = { version = "*", features = [ "serde" ] }
wasm-bindgen = "*"
js-sys = "*"
futures = "^0.1.26"

[dependencies.web-sys]
version = "*"
features = [
    "Window",
    "DataTransfer",
    "DragEvent",
    "HtmlDivElement",
    "DomRect"
]
