[package]
name = "jirs-client"
version = "0.1.0"
authors = ["Adrian Wozniak <adrian.wozniak@ita-prog.pl>"]
edition = "2018"
description = "JIRS (Simplified JIRA in Rust) WASM client"
repository = "https://gitlab.com/adrian.wozniak/jirs"
license = "MPL-2.0"
#license-file = "../LICENSE"

[lib]
crate-type = ["cdylib", "rlib"]
name = "jirs_client"
path = "./src/lib.rs"

[dependencies]
jirs-data = { path = "../jirs-data" }
seed = { version = "*" }
serde = "*"
serde_json = "*"
bincode = "1.2.1"
chrono = { version = "*", features = [ "serde" ] }
uuid = { version = "*", features = [ "serde" ] }
wasm-bindgen = "0.2.60"
futures = "^0.1.26"
comrak = "*"

[dependencies.js-sys]
version = "*"

[dependencies.web-sys]
version = "0.3.22"
features = [
    "Window",
    "DataTransfer",
    "DragEvent",
    "HtmlDivElement",
    "DomRect",
    "HtmlDocument",
    "Document",
    "Selection",
    "CssStyleDeclaration",
    "WebSocket",
    "BinaryType",
    "Blob",
    "MessageEvent",
    "ErrorEvent",
]
