# For documentation on how to configure this file,
# see diesel.rs/guides/configuring-diesel-cli

[print_schema]
file = "actors/database-actor/src/schema.rs"
import_types = ["diesel::sql_types::*", "jirs_data::*"]
with_docs = true
patch_file = "./actors/database-actor/src/schema.patch"
