version: '3.2'

services:
  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_HOST_AUTH_METHOD=trust

  build-server:
    build:
      dockerfile: ./Dockerfile.build
      context: .
    stdin_open: true
    tty: true
    volumes:
      - ./build:/app/build
      - type: volume
        source: rs-target
        target: /app/jirs-server/target
      - ./Cargo.toml:/app/Cargo.toml
      - ./Cargo.lock:/app/Cargo.lock
      - ./jirs-server:/app/jirs-server
      - ./jirs-data:/app/jirs-data
      - ./jirs-cli:/app/jirs-cli
      - ./jirs-client:/app/jirs-client
      - ./jirs-css:/app/jirs-css
  server:
    build:
      dockerfile: ./jirs-server/Dockerfile
      context: .
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://postgres@db/jirs
      - JIRS_SERVER_PORT=5000
      - JIRS_SERVER_BIND=0.0.0.0
      - RUST_LOG=debug
      - DEBUG=true
      - JIRS_CLIENT_PORT=7000
      - JIRS_CLIENT_BIND=0.0.0.0

  nginx:
    image: nginx:latest
    depends_on:
      - client
      - server
    ports:
      - 80:80
    volumes:
      - ./.builds/nginx.conf:/etc/nginx/conf.d/default.conf
      - type: volume
        source: assets
        target: /assets
        volume:
          nocopy: true

  client:
    build:
      dockerfile: ./jirs-client/Dockerfile
      context: .
    env_file:
      - .env
    environment:
      - JIRS_SERVER_PORT=80
      - JIRS_SERVER_BIND=jirs.lvh.me
      - JIRS_CLIENT_PORT=80
      - JIRS_CLIENT_BIND=jirs.lvh.me
    volumes:
      - type: volume
        source: assets
        target: /assets
        volume:
          nocopy: true

volumes:
  assets:
  build:
  rs-target:
