version: '3.2'

services:
  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_HOST_AUTH_METHOD=trust

  server:
    build:
      dockerfile: ./jirs-server/Dockerfile
      context: .
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://postgres@db/jirs
      - JIRS_SERVER_PORT=5000
      - JIRS_SERVER_BIND=0.0.0.0
      - RUST_LOG=debug
      - DEBUG=true
      - JIRS_CLIENT_PORT=7000
      - JIRS_CLIENT_BIND=0.0.0.0

  nginx:
    image: nginx:latest
    depends_on:
      - client
      - server
    ports:
      - 80:80
    volumes:
      - ./.builds/nginx.conf:/etc/nginx/conf.d/default.conf
      - type: volume
        source: assets
        target: /assets
        volume:
          nocopy: true

  client:
    build:
      dockerfile: ./jirs-client/Dockerfile
      context: .
    env_file:
      - .env
    environment:
      - JIRS_SERVER_PORT=80
      - JIRS_SERVER_BIND=jirs.lvh.me
      - JIRS_CLIENT_PORT=80
      - JIRS_CLIENT_BIND=jirs.lvh.me
    volumes:
      - type: volume
        source: assets
        target: /assets
        volume:
          nocopy: true

volumes:
  assets:
