
#![allow(unused_imports)]
#![allow(dead_code)]

use jirs_syntect::{*, parsing::*};
use lazycell::AtomicLazyCell;

#[inline(always)]
pub fn load() -> SyntaxReference {
        SyntaxReference {  name: "Friendly Interactive Shell (fish)".to_string(),
  file_extensions: vec!["fish".to_string()],
  scope: Scope { a: 844742764658688, b: 0 },
  first_line_match: Some("^#!.*\\b(fish)\\b".to_string()),
  hidden: false,
  variables: {
    let mut v = std::collections::HashMap::new();
    v.insert("real".to_string(), "(?:{{int}}\\.?[0-9]*|[+-]?[0-9]*\\.?[0-9]+)".to_string());
    v.insert("op_w".to_string(), "[{{nl_w}}]|;|&(?![|>])".to_string());
    v.insert("op_s".to_string(), ";&".to_string());
    v.insert("int".to_string(), "[+-]?[0-9]+".to_string());
    v.insert("ws_sep".to_string(), "[^\\n\\S]".to_string());
    v.insert("nl_s".to_string(), "\\n\\)".to_string());
    v.insert("op_w_pipe".to_string(), "{{op_w}}|{{pipe_w}}".to_string());
    v.insert("redir_s".to_string(), "<>".to_string());
    v.insert("op_w_pipe_redir".to_string(), "{{op_w}}|{{pipe_w}}|{{redir_w}}".to_string());
    v.insert("_redir_base".to_string(), "(?:[0-9]+)?(?:[{{redir_s}}]|>>)|\\^\\^?".to_string());
    v.insert("pipe_w".to_string(), "(?:{{_redir_base}}|&)?{{pipe_s}}".to_string());
    v.insert("id_var".to_string(), "\\w".to_string());
    v.insert("op_w_redir".to_string(), "{{op_w}}|{{redir_w}}".to_string());
    v.insert("pipe_s".to_string(), "\\|".to_string());
    v.insert("redir_w".to_string(), "{{_redir_base}}|&>>?".to_string());
    v.insert("nl_w".to_string(), "{{nl_s}}#".to_string());
    v.insert("param_sep".to_string(), "{{ws_sep}}{{nl_s}}{{op_s}}{{pipe_s}}{{redir_s}}".to_string());
    v
  },
  contexts: {
    let mut v = std::collections::HashMap::new();
    v.insert("#anon_command-substitution_1".to_string(), ContextId { index: 7139 });
    v.insert("#anon_command-call-standard-block_18".to_string(), ContextId { index: 7113 });
    v.insert("#anon_pipeline_1".to_string(), ContextId { index: 7165 });
    v.insert("#anon_redirection-to-file-path-lhs+op_3".to_string(), ContextId { index: 7182 });
    v.insert("__start".to_string(), ContextId { index: 7221 });
    v.insert("#anon_command-call-standard-block_22".to_string(), ContextId { index: 7118 });
    v.insert("redirection-common-lhs+op".to_string(), ContextId { index: 7244 });
    v.insert("#anon_string-unquoted-patterns_0".to_string(), ContextId { index: 7209 });
    v.insert("#anon_command-call-standard-block_17".to_string(), ContextId { index: 7112 });
    v.insert("#anon_redirection-to-file-path-lhs+op_4".to_string(), ContextId { index: 7183 });
    v.insert("#anon_redirection-to-pipe-lhs+op_6".to_string(), ContextId { index: 7197 });
    v.insert("#anon_redirection-to-pipe-lhs+op_5".to_string(), ContextId { index: 7196 });
    v.insert("pipeline-segment".to_string(), ContextId { index: 7239 });
    v.insert("#anon_variable-expansion_0".to_string(), ContextId { index: 7219 });
    v.insert("#anon_command-call-environment_2".to_string(), ContextId { index: 7092 });
    v.insert("pipeline".to_string(), ContextId { index: 7238 });
    v.insert("#anon_redirection_3".to_string(), ContextId { index: 7204 });
    v.insert("#anon_line-continuation_0".to_string(), ContextId { index: 7142 });
    v.insert("#anon_command-call-standard_0".to_string(), ContextId { index: 7132 });
    v.insert("#anon_string-quoted_0".to_string(), ContextId { index: 7207 });
    v.insert("#anon_command-call-meta_3".to_string(), ContextId { index: 7096 });
    v.insert("#anon_parameter-argument_1".to_string(), ContextId { index: 7146 });
    v.insert("#anon_parameter-argument_0".to_string(), ContextId { index: 7145 });
    v.insert("command-call-standard-block-if-internal".to_string(), ContextId { index: 7226 });
    v.insert("#anon_command-call-standard-block-if-internal_5".to_string(), ContextId { index: 7102 });
    v.insert("command-call-standard".to_string(), ContextId { index: 7224 });
    v.insert("redirection-to-file-descriptor-rhs".to_string(), ContextId { index: 7248 });
    v.insert("#anon_redirection_1".to_string(), ContextId { index: 7202 });
    v.insert("#anon_redirection_0".to_string(), ContextId { index: 7201 });
    v.insert("#anon_command-call-environment_1".to_string(), ContextId { index: 7091 });
    v.insert("#anon_redirection-common-lhs+op_7".to_string(), ContextId { index: 7173 });
    v.insert("#anon_parameter-option_2".to_string(), ContextId { index: 7153 });
    v.insert("#anon_command-call-standard-block_10".to_string(), ContextId { index: 7105 });
    v.insert("#anon_command-call-standard-block_15".to_string(), ContextId { index: 7110 });
    v.insert("#anon_command-call-standard-block_9".to_string(), ContextId { index: 7126 });
    v.insert("#anon_command-call-environment_0".to_string(), ContextId { index: 7090 });
    v.insert("#anon_redirection-to-pipe-lhs+op_10".to_string(), ContextId { index: 7191 });
    v.insert("command-call-standard-name".to_string(), ContextId { index: 7227 });
    v.insert("#anon_redirection-to-file-descriptor-rhs_2".to_string(), ContextId { index: 7178 });
    v.insert("#anon_command-call-standard-block_1".to_string(), ContextId { index: 7104 });
    v.insert("#anon_command-call-standard-block_13".to_string(), ContextId { index: 7108 });
    v.insert("#anon_index-expansion_0".to_string(), ContextId { index: 7141 });
    v.insert("redirection".to_string(), ContextId { index: 7242 });
    v.insert("redirection-common-lhs".to_string(), ContextId { index: 7243 });
    v.insert("__main".to_string(), ContextId { index: 7220 });
    v.insert("#anon_parameter-common_0".to_string(), ContextId { index: 7150 });
    v.insert("#anon_command-call-standard-block-if-internal_1".to_string(), ContextId { index: 7098 });
    v.insert("#anon_command-call-standard-block_8".to_string(), ContextId { index: 7125 });
    v.insert("#anon_pipeline-segment-piping_0".to_string(), ContextId { index: 7157 });
    v.insert("#anon_command-call-standard-block_11".to_string(), ContextId { index: 7106 });
    v.insert("#anon_string-unquoted-patterns_1".to_string(), ContextId { index: 7210 });
    v.insert("#anon_command-call-standard-name_2".to_string(), ContextId { index: 7129 });
    v.insert("#anon_command-call-standard_3".to_string(), ContextId { index: 7135 });
    v.insert("#anon_string-unquoted-patterns_2".to_string(), ContextId { index: 7211 });
    v.insert("#anon_command-call-standard-block_4".to_string(), ContextId { index: 7121 });
    v.insert("#anon_string-unquoted-patterns_6".to_string(), ContextId { index: 7215 });
    v.insert("parameter-option".to_string(), ContextId { index: 7236 });
    v.insert("#anon_command-call-standard-block_12".to_string(), ContextId { index: 7107 });
    v.insert("#anon_redirection-to-file-path-rhs_2".to_string(), ContextId { index: 7186 });
    v.insert("#anon_redirection-to-file-path-rhs_0".to_string(), ContextId { index: 7184 });
    v.insert("string-quoted".to_string(), ContextId { index: 7254 });
    v.insert("#anon_command-call-meta_2".to_string(), ContextId { index: 7095 });
    v.insert("#anon_string-unquoted-patterns_3".to_string(), ContextId { index: 7212 });
    v.insert("string-unquoted".to_string(), ContextId { index: 7255 });
    v.insert("#anon_redirection-common-lhs+op_0".to_string(), ContextId { index: 7166 });
    v.insert("#anon_redirection-common-lhs+op_8".to_string(), ContextId { index: 7174 });
    v.insert("#anon_parameter-option_3".to_string(), ContextId { index: 7154 });
    v.insert("#anon_command-call-standard-block_7".to_string(), ContextId { index: 7124 });
    v.insert("pipeline-segment-between".to_string(), ContextId { index: 7240 });
    v.insert("#anon_string-unquoted-patterns_5".to_string(), ContextId { index: 7214 });
    v.insert("#anon_redirection-common-lhs+op_1".to_string(), ContextId { index: 7167 });
    v.insert("redirection-common-op-write-caret".to_string(), ContextId { index: 7247 });
    v.insert("#anon_command-call-standard-block-if-internal_4".to_string(), ContextId { index: 7101 });
    v.insert("#anon_string-unquoted-patterns_7".to_string(), ContextId { index: 7216 });
    v.insert("#anon_command-call-standard-block-if-internal_0".to_string(), ContextId { index: 7097 });
    v.insert("#anon_comment_0".to_string(), ContextId { index: 7140 });
    v.insert("command-call-meta".to_string(), ContextId { index: 7223 });
    v.insert("#anon_redirection-common-lhs+op_2".to_string(), ContextId { index: 7168 });
    v.insert("#anon_command-call-standard-name_1".to_string(), ContextId { index: 7128 });
    v.insert("command-call-environment".to_string(), ContextId { index: 7222 });
    v.insert("#anon_redirection-common-lhs+op_6".to_string(), ContextId { index: 7172 });
    v.insert("#anon_redirection_2".to_string(), ContextId { index: 7203 });
    v.insert("#anon_redirection-to-file-path-lhs+op_1".to_string(), ContextId { index: 7180 });
    v.insert("#anon_pipeline-segment_4".to_string(), ContextId { index: 7162 });
    v.insert("redirection-to-file-path-lhs+op".to_string(), ContextId { index: 7249 });
    v.insert("#anon_parameter-argument_2".to_string(), ContextId { index: 7147 });
    v.insert("#anon_command-call-standard-block_23".to_string(), ContextId { index: 7119 });
    v.insert("#anon_command-call-standard-block_14".to_string(), ContextId { index: 7109 });
    v.insert("#anon_pipeline-segment_1".to_string(), ContextId { index: 7159 });
    v.insert("#anon_command-call-standard_5".to_string(), ContextId { index: 7137 });
    v.insert("#anon_command-call-standard_1".to_string(), ContextId { index: 7133 });
    v.insert("#anon_parameter-option_4".to_string(), ContextId { index: 7155 });
    v.insert("#anon_variable-expansion-simple_0".to_string(), ContextId { index: 7218 });
    v.insert("#anon_parameter-option_5".to_string(), ContextId { index: 7156 });
    v.insert("#anon_redirection-to-pipe-lhs+op_2".to_string(), ContextId { index: 7193 });
    v.insert("variable-expansion".to_string(), ContextId { index: 7259 });
    v.insert("#anon_redirection-to-pipe-lhs+op_4".to_string(), ContextId { index: 7195 });
    v.insert("#anon_main_0".to_string(), ContextId { index: 7143 });
    v.insert("#anon_redirection_4".to_string(), ContextId { index: 7205 });
    v.insert("#anon_redirection_5".to_string(), ContextId { index: 7206 });
    v.insert("#anon_main_1".to_string(), ContextId { index: 7144 });
    v.insert("#anon_command-call-standard-block_16".to_string(), ContextId { index: 7111 });
    v.insert("redirection-common-op-read".to_string(), ContextId { index: 7245 });
    v.insert("#anon_redirection-to-pipe-lhs+op_8".to_string(), ContextId { index: 7199 });
    v.insert("redirection-to-pipe-lhs+op".to_string(), ContextId { index: 7251 });
    v.insert("#anon_redirection-to-pipe-lhs+op_0".to_string(), ContextId { index: 7189 });
    v.insert("string-unquoted-patterns-escapes".to_string(), ContextId { index: 7257 });
    v.insert("#anon_pipeline-segment_3".to_string(), ContextId { index: 7161 });
    v.insert("pipeline-segment-piping".to_string(), ContextId { index: 7241 });
    v.insert("#anon_redirection-to-pipe-lhs+op_3".to_string(), ContextId { index: 7194 });
    v.insert("#anon_parameter-option_0".to_string(), ContextId { index: 7151 });
    v.insert("#anon_redirection-to-file-path-rhs_1".to_string(), ContextId { index: 7185 });
    v.insert("#anon_command-call-standard-block-if-internal_3".to_string(), ContextId { index: 7100 });
    v.insert("#anon_redirection-to-pipe-lhs+op_1".to_string(), ContextId { index: 7190 });
    v.insert("#anon_redirection-common-lhs+op_5".to_string(), ContextId { index: 7171 });
    v.insert("#anon_redirection-to-file-path-rhs_3".to_string(), ContextId { index: 7187 });
    v.insert("#anon_string-unquoted_0".to_string(), ContextId { index: 7217 });
    v.insert("parameter-argument".to_string(), ContextId { index: 7234 });
    v.insert("#anon_redirection-to-file-path-rhs_4".to_string(), ContextId { index: 7188 });
    v.insert("#anon_string-unquoted-patterns_4".to_string(), ContextId { index: 7213 });
    v.insert("string-unquoted-patterns-escapes-newline".to_string(), ContextId { index: 7258 });
    v.insert("#anon_redirection-to-pipe-lhs+op_7".to_string(), ContextId { index: 7198 });
    v.insert("#anon_command-call-standard_2".to_string(), ContextId { index: 7134 });
    v.insert("redirection-common-op-write".to_string(), ContextId { index: 7246 });
    v.insert("#anon_command-call-standard-block_19".to_string(), ContextId { index: 7114 });
    v.insert("string-unquoted-patterns".to_string(), ContextId { index: 7256 });
    v.insert("#anon_pipeline-segment_0".to_string(), ContextId { index: 7158 });
    v.insert("#anon_redirection-to-pipe-lhs+op_11".to_string(), ContextId { index: 7192 });
    v.insert("#anon_pipeline-segment_2".to_string(), ContextId { index: 7160 });
    v.insert("line-continuation".to_string(), ContextId { index: 7231 });
    v.insert("#anon_command-call-standard-name_0".to_string(), ContextId { index: 7127 });
    v.insert("main".to_string(), ContextId { index: 7232 });
    v.insert("#anon_command-call-standard-block_3".to_string(), ContextId { index: 7120 });
    v.insert("#anon_redirection-to-file-descriptor-rhs_1".to_string(), ContextId { index: 7177 });
    v.insert("#anon_command-call-meta_1".to_string(), ContextId { index: 7094 });
    v.insert("#anon_command-call-standard-block_2".to_string(), ContextId { index: 7115 });
    v.insert("#anon_command-call-standard-block_20".to_string(), ContextId { index: 7116 });
    v.insert("command-substitution".to_string(), ContextId { index: 7228 });
    v.insert("#anon_redirection-to-file-path-lhs+op_0".to_string(), ContextId { index: 7179 });
    v.insert("parameter-common".to_string(), ContextId { index: 7235 });
    v.insert("pipe-common".to_string(), ContextId { index: 7237 });
    v.insert("redirection-to-file-path-rhs".to_string(), ContextId { index: 7250 });
    v.insert("parameter".to_string(), ContextId { index: 7233 });
    v.insert("#anon_command-call-standard-block_0".to_string(), ContextId { index: 7103 });
    v.insert("#anon_redirection-common-lhs+op_4".to_string(), ContextId { index: 7170 });
    v.insert("#anon_redirection-to-file-descriptor-rhs_0".to_string(), ContextId { index: 7176 });
    v.insert("string".to_string(), ContextId { index: 7253 });
    v.insert("variable-expansion-simple".to_string(), ContextId { index: 7261 });
    v.insert("command-call-standard-block".to_string(), ContextId { index: 7225 });
    v.insert("#anon_command-call-standard-name_4".to_string(), ContextId { index: 7131 });
    v.insert("comment".to_string(), ContextId { index: 7229 });
    v.insert("#anon_string-quoted_1".to_string(), ContextId { index: 7208 });
    v.insert("#anon_pipeline_0".to_string(), ContextId { index: 7164 });
    v.insert("#anon_command-call-meta_0".to_string(), ContextId { index: 7093 });
    v.insert("#anon_command-call-standard-block_5".to_string(), ContextId { index: 7122 });
    v.insert("#anon_redirection-to-file-path-lhs+op_2".to_string(), ContextId { index: 7181 });
    v.insert("variable-expansion-illegal".to_string(), ContextId { index: 7260 });
    v.insert("#anon_pipeline-segment_5".to_string(), ContextId { index: 7163 });
    v.insert("#anon_parameter-option_1".to_string(), ContextId { index: 7152 });
    v.insert("index-expansion".to_string(), ContextId { index: 7230 });
    v.insert("#anon_command-call-standard-name_3".to_string(), ContextId { index: 7130 });
    v.insert("#anon_command-call-standard-block_21".to_string(), ContextId { index: 7117 });
    v.insert("#anon_command-call-standard_4".to_string(), ContextId { index: 7136 });
    v.insert("#anon_command-substitution_0".to_string(), ContextId { index: 7138 });
    v.insert("#anon_redirection-common-lhs+op_3".to_string(), ContextId { index: 7169 });
    v.insert("#anon_command-call-standard-block_6".to_string(), ContextId { index: 7123 });
    v.insert("#anon_redirection-to-pipe-lhs+op_9".to_string(), ContextId { index: 7200 });
    v.insert("#anon_parameter-argument_4".to_string(), ContextId { index: 7149 });
    v.insert("#anon_redirection-common-lhs+op_9".to_string(), ContextId { index: 7175 });
    v.insert("separator-whitespace".to_string(), ContextId { index: 7252 });
    v.insert("#anon_parameter-argument_3".to_string(), ContextId { index: 7148 });
    v.insert("#anon_command-call-standard-block-if-internal_2".to_string(), ContextId { index: 7099 });
    v
  }
} }