
#![allow(unused_imports)]
#![allow(dead_code)]

use jirs_syntect::{*, parsing::*};
use lazycell::AtomicLazyCell;

#[inline(always)]
pub fn load() -> SyntaxReference {
        SyntaxReference {  name: "Less".to_string(),
  file_extensions: vec!["less".to_string(),"css.less".to_string()],
  scope: Scope { a: 844953211109376, b: 0 },
  first_line_match: None,
  hidden: false,
  variables: {
    let mut v = std::collections::HashMap::new();
    v.insert("frequency_units".to_string(), "(?i:Hz|kHz)".to_string());
    v.insert("functional_pseudo_classes".to_string(), "\\b(dir|lang|matches|not|has|drop|nth-last-child|nth-child|nth-last-of-type|nth-of-type)\\b".to_string());
    v.insert("resolution_units".to_string(), "(?i:dpi|dpcm|dppx)".to_string());
    v.insert("nmchar".to_string(), "(?:[[-\\w]{{nonascii}}]|{{escape}})".to_string());
    v.insert("pseudo_elements".to_string(), "(?x:\n    (:{1,2})(?:before|after|first-line|first-letter) # CSS1 & CSS2 require : or ::\n  | (::)(-(?:moz|ms|webkit)-)?(?:{{ident}}) # CSS3 requires ::\n)\\b".to_string());
    v.insert("angle_units".to_string(), "(?i:deg|grad|rad|turn)".to_string());
    v.insert("exponent".to_string(), "(?:[eE]{{integer}})".to_string());
    v.insert("ident".to_string(), "(?:--{{nmchar}}+|-?{{nmstart}}{{nmchar}}*)".to_string());
    v.insert("integer".to_string(), "(?:[-+]?\\d+)".to_string());
    v.insert("absolute_lengths".to_string(), "(?i:cm|mm|q|in|pt|pc|px|fr)".to_string());
    v.insert("duration_units".to_string(), "(?i:s|ms)".to_string());
    v.insert("escape".to_string(), "(?:{{unicode}}|\\\\[^\\n\\f\\h])".to_string());
    v.insert("nonascii".to_string(), "[\\p{L}\\p{M}\\p{S}\\p{N}&&[^[:ascii:]]]".to_string());
    v.insert("custom_element_chars".to_string(), "(?x:\n    [-_a-z0-9\\x{00B7}]\n  | \\\\\\.\n  | [\\x{00C0}-\\x{00D6}]\n  | [\\x{00D8}-\\x{00F6}]\n  | [\\x{00F8}-\\x{02FF}]\n  | [\\x{0300}-\\x{037D}]\n  | [\\x{037F}-\\x{1FFF}]\n  | [\\x{200C}-\\x{200D}]\n  | [\\x{203F}-\\x{2040}]\n  | [\\x{2070}-\\x{218F}]\n  | [\\x{2C00}-\\x{2FEF}]\n  | [\\x{3001}-\\x{D7FF}]\n  | [\\x{F900}-\\x{FDCF}]\n  | [\\x{FDF0}-\\x{FFFD}]\n  | [\\x{10000}-\\x{EFFFF}]\n)".to_string());
    v.insert("unicode".to_string(), "\\\\\\h{1,6}[ \\t\\n\\f]?".to_string());
    v.insert("viewport_percentage_lengths".to_string(), "(?i:vw|vh|vmin|vmax)".to_string());
    v.insert("font_relative_lengths".to_string(), "(?i:em|ex|ch|rem)".to_string());
    v.insert("nmstart".to_string(), "(?:[[_a-zA-Z]{{nonascii}}]|{{escape}})".to_string());
    v.insert("combinators".to_string(), "(?:>{1,3}|[~+])".to_string());
    v.insert("counter_styles".to_string(), "(?xi:\n    arabic-indic | armenian | bengali | cambodian | circle\n  | cjk-decimal | cjk-earthly-branch | cjk-heavenly-stem | decimal-leading-zero\n  | decimal | devanagari | disclosure-closed | disclosure-open | disc\n  | ethiopic-numeric | georgian | gujarati | gurmukhi | hebrew\n  | hiragana-iroha | hiragana | japanese-formal | japanese-informal\n  | kannada | katakana-iroha | katakana | khmer\n  | korean-hangul-formal | korean-hanja-formal | korean-hanja-informal | lao\n  | lower-alpha | lower-armenian | lower-greek | lower-latin | lower-roman\n  | malayalam | mongolian | myanmar | oriya | persian\n  | simp-chinese-formal | simp-chinese-informal\n  | square | tamil | telugu | thai | tibetan\n  | trad-chinese-formal | trad-chinese-informal\n  | upper-alpha | upper-armenian | upper-latin | upper-roman\n)".to_string());
    v.insert("custom_elements".to_string(), "\\b([a-z](?:{{custom_element_chars}})*-(?:{{custom_element_chars}})*)\\b(?!{{ident}})".to_string());
    v.insert("element_names".to_string(), "\\b(a|abbr|acronym|address|applet|area|article|aside|audio|b|base|basefont|bdi|bdo|big|blockquote|body|br|button|canvas|caption|cite|code|col|colgroup|content|data|datalist|dd|del|details|dfn|dir|dialog|div|dl|dt|element|em|embed|eventsource|fieldset|figure|figcaption|footer|form|frame|frameset|h[1-6]|head|header|hgroup|hr|html|i|iframe|img|input|ins|isindex|kbd|keygen|label|legend|li|link|main|map|mark|menu|meta|meter|nav|noframes|noscript|object|ol|optgroup|option|output|p|param|picture|pre|progress|q|rp|rt|rtc|s|samp|script|section|select|shadow|small|source|span|strike|strong|style|sub|summary|sup|svg|table|tbody|td|template|textarea|tfoot|th|thead|time|title|tr|track|tt|u|ul|var|video|wbr|xmp|circle|clipPath|defs|ellipse|filter|foreignObject|g|glyph|glyphRef|image|line|linearGradient|marker|mask|path|pattern|polygon|polyline|radialGradient|rect|stop|switch|symbol|text|textPath|tref|tspan|use)\\b".to_string());
    v.insert("property_names".to_string(), "\\b(?x)(\n    display|width|background-color|height|position|font-family|font-weight\n  | top|opacity|cursor|background-image|right|visibility|box-sizing\n  | user-select|left|float|margin-left|margin-top|line-height\n  | padding-left|z-index|margin-bottom|margin-right|margin\n  | vertical-align|padding-top|white-space|border-radius|padding-bottom\n  | padding-right|padding|bottom|clear|max-width|box-shadow|content\n  | border-color|min-height|min-width|font-style|border-width\n  | border-collapse|background-size|text-overflow|max-height|text-transform\n  | text-shadow|text-indent|border-style|overflow-y|list-style-type\n  | word-wrap|border-spacing|appearance|zoom|overflow-x|border-top-left-radius\n  | border-bottom-left-radius|border-top-color|pointer-events\n  | border-bottom-color|align-items|justify-content|letter-spacing\n  | border-top-right-radius|border-bottom-right-radius|border-right-width\n  | font-smoothing|border-bottom-width|border-right-color|direction\n  | border-top-width|src|border-left-color|border-left-width\n  | tap-highlight-color|table-layout|background-clip|word-break\n  | transform-origin|resize|filter|backface-visibility|text-rendering\n  | box-orient|transition-property|transition-duration|word-spacing\n  | quotes|outline-offset|animation-timing-function|animation-duration\n  | animation-name|transition-timing-function|border-bottom-style\n  | border-bottom|transition-delay|transition|unicode-bidi|border-top-style\n  | border-top|unicode-range|list-style-position|orphans|outline-width\n  | line-clamp|order|flex-direction|box-pack|animation-fill-mode\n  | outline-color|list-style-image|list-style|touch-action|flex-grow\n  | border-left-style|border-left|animation-iteration-count\n  | page-break-inside|box-flex|box-align|page-break-after|animation-delay\n  | widows|border-right-style|border-right|flex-align|outline-style\n  | outline|background-origin|animation-direction|fill-opacity\n  | background-attachment|flex-wrap|transform-style|counter-increment\n  | overflow-wrap|counter-reset|animation-play-state|animation\n  | will-change|box-ordinal-group|image-rendering|mask-image|flex-flow\n  | background-position-y|stroke-width|background-position-x|background-position\n  | background-blend-mode|flex-shrink|flex-basis|flex-order|flex-item-align\n  | flex-line-pack|flex-negative|flex-pack|flex-positive|flex-preferred-size\n  | flex|user-drag|font-stretch|column-count|empty-cells|align-self\n  | caption-side|mask-size|column-gap|mask-repeat|box-direction\n  | font-feature-settings|mask-position|align-content|object-fit\n  | columns|text-fill-color|clip-path|stop-color|font-kerning\n  | page-break-before|stroke-dasharray|size|fill-rule|border-image-slice\n  | column-width|break-inside|column-break-before|border-image-width\n  | stroke-dashoffset|border-image-repeat|border-image-outset|line-break\n  | stroke-linejoin|stroke-linecap|stroke-miterlimit|stroke-opacity\n  | stroke|shape-rendering|border-image-source|border-image|border\n  | tab-size|writing-mode|perspective-origin-y|perspective-origin-x\n  | perspective-origin|perspective|text-align-last|text-align|clip-rule\n  | clip|text-anchor|column-rule-color|box-decoration-break|column-fill\n  | fill|column-rule-style|mix-blend-mode|text-emphasis-color\n  | baseline-shift|dominant-baseline|page|alignment-baseline\n  | column-rule-width|column-rule|break-after|font-variant-ligatures\n  | transform-origin-y|transform-origin-x|transform|object-position\n  | break-before|column-span|isolation|shape-outside|all\n  | color-interpolation-filters|marker|marker-end|marker-start\n  | marker-mid|color-rendering|color-interpolation|background-repeat-x\n  | background-repeat-y|background-repeat|background|mask-type\n  | flood-color|flood-opacity|text-orientation|mask-composite\n  | text-emphasis-style|paint-order|lighting-color|shape-margin\n  | text-emphasis-position|text-emphasis|shape-image-threshold\n  | mask-clip|mask-origin|mask|font-variant-caps|font-variant-alternates\n  | font-variant-east-asian|font-variant-numeric|font-variant-position\n  | font-variant|font-size-adjust|font-size|font-language-override\n  | font-display|font-synthesis|font|line-box-contain|text-justify\n  | text-decoration-color|text-decoration-style|text-decoration-line\n  | text-decoration|text-underline-position|grid-template-rows\n  | grid-template-columns|grid-template-areas|grid-template|rotate|scale\n  | translate|scroll-behavior|grid-column-start|grid-column-end\n  | grid-column-gap|grid-row-start|grid-row-end|grid-auto-rows\n  | grid-area|grid-auto-flow|grid-auto-columns|image-orientation\n  | hyphens|overflow-scrolling|overflow|color-profile|kerning\n  | nbsp-mode|color|image-resolution|grid-row-gap|grid-row|grid-column\n  | blend-mode|azimuth|pause-after|pause-before|pause|pitch-range|pitch\n  | text-height|system|negative|prefix|suffix|range|pad|fallback\n  | additive-symbols|symbols|speak-as|speak|grid-gap\n)\\b".to_string());
    v.insert("float".to_string(), "(?x:\n  [-+]? \\d* (\\.) \\d+ {{exponent}}?\n| [-+]? \\d+          {{exponent}}\n)".to_string());
    v.insert("regular_pseudo_classes".to_string(), "\\b(active|any-link|blank|checked|current|default|defined|disabled|drop|empty|enabled|first|first-child|first-of-type|fullscreen|future|focus|focus-visible|focus-within|host|hover|indeterminate|in-range|invalid|last-child|last-of-type|left|link|local-link|only-child|only-of-type|optional|out-of-range|past|placeholder-shown|read-only|read-write|required|right|root|scope|target|target-within|user-invalid|valid|visited)\\b(?![-])".to_string());
    v
  },
  contexts: {
    let mut v = std::collections::HashMap::new();
    v.insert("keyframe-operators".to_string(), ContextId { index: 8295 });
    v.insert("at-supports-operators".to_string(), ContextId { index: 8267 });
    v.insert("#anon_color-functions_4".to_string(), ContextId { index: 8162 });
    v.insert("#anon_interpolated-selectors_1".to_string(), ContextId { index: 8203 });
    v.insert("selectors".to_string(), ContextId { index: 8323 });
    v.insert("#anon_builtin-functions_40".to_string(), ContextId { index: 8136 });
    v.insert("unicode-range".to_string(), ContextId { index: 8326 });
    v.insert("#anon_builtin-functions_35".to_string(), ContextId { index: 8130 });
    v.insert("literal-string".to_string(), ContextId { index: 8306 });
    v.insert("__main".to_string(), ContextId { index: 8262 });
    v.insert("#anon_builtin-functions_7".to_string(), ContextId { index: 8144 });
    v.insert("property-value-wrapper".to_string(), ContextId { index: 8315 });
    v.insert("#anon_builtin-functions_32".to_string(), ContextId { index: 8127 });
    v.insert("#anon_url-function_1".to_string(), ContextId { index: 8257 });
    v.insert("percentage-type".to_string(), ContextId { index: 8312 });
    v.insert("#anon_builtin-functions_30".to_string(), ContextId { index: 8125 });
    v.insert("#anon_filter-functions_2".to_string(), ContextId { index: 8188 });
    v.insert("url-function".to_string(), ContextId { index: 8328 });
    v.insert("#anon_cross-fade-function_1".to_string(), ContextId { index: 8171 });
    v.insert("#anon_image-function_0".to_string(), ContextId { index: 8198 });
    v.insert("length-type".to_string(), ContextId { index: 8296 });
    v.insert("#anon_custom-element-selectors_10".to_string(), ContextId { index: 8174 });
    v.insert("#anon_builtin-functions_0".to_string(), ContextId { index: 8101 });
    v.insert("#anon_color-functions_7".to_string(), ContextId { index: 8165 });
    v.insert("#anon_var-function_1".to_string(), ContextId { index: 8261 });
    v.insert("#anon_attr-function_1".to_string(), ContextId { index: 8099 });
    v.insert("#anon_builtin-functions_33".to_string(), ContextId { index: 8128 });
    v.insert("#anon_custom-element-selectors_0".to_string(), ContextId { index: 8172 });
    v.insert("#anon_at-rules_0".to_string(), ContextId { index: 8085 });
    v.insert("line-names".to_string(), ContextId { index: 8305 });
    v.insert("#anon_color-functions_0".to_string(), ContextId { index: 8158 });
    v.insert("at-rule-punctuation".to_string(), ContextId { index: 8265 });
    v.insert("#anon_builtin-functions_34".to_string(), ContextId { index: 8129 });
    v.insert("#anon_at-rules_8".to_string(), ContextId { index: 8095 });
    v.insert("#anon_builtin-functions_5".to_string(), ContextId { index: 8142 });
    v.insert("#anon_selectors_3".to_string(), ContextId { index: 8249 });
    v.insert("#anon_var-function_0".to_string(), ContextId { index: 8260 });
    v.insert("#anon_builtin-functions_44".to_string(), ContextId { index: 8140 });
    v.insert("less-map-values".to_string(), ContextId { index: 8301 });
    v.insert("#anon_property-value-wrapper_0".to_string(), ContextId { index: 8232 });
    v.insert("#anon_filter-functions_6".to_string(), ContextId { index: 8192 });
    v.insert("#anon_color-adjuster-functions_1".to_string(), ContextId { index: 8149 });
    v.insert("color-adjuster-operators".to_string(), ContextId { index: 8273 });
    v.insert("#anon_custom-element-selectors_2".to_string(), ContextId { index: 8176 });
    v.insert("#anon_at-rules_9".to_string(), ContextId { index: 8096 });
    v.insert("#anon_less-aliases_1".to_string(), ContextId { index: 8208 });
    v.insert("builtin-functions".to_string(), ContextId { index: 8270 });
    v.insert("#anon_minmax-function_0".to_string(), ContextId { index: 8223 });
    v.insert("#anon_builtin-functions_6".to_string(), ContextId { index: 8143 });
    v.insert("#anon_builtin-functions_36".to_string(), ContextId { index: 8131 });
    v.insert("#anon_color-adjuster-functions_9".to_string(), ContextId { index: 8157 });
    v.insert("attr-function".to_string(), ContextId { index: 8269 });
    v.insert("image-function".to_string(), ContextId { index: 8289 });
    v.insert("main".to_string(), ContextId { index: 8307 });
    v.insert("less-aliases".to_string(), ContextId { index: 8297 });
    v.insert("less-interpolation".to_string(), ContextId { index: 8299 });
    v.insert("#anon_selectors_6".to_string(), ContextId { index: 8252 });
    v.insert("#anon_builtin-functions_13".to_string(), ContextId { index: 8106 });
    v.insert("#anon_less-variables_0".to_string(), ContextId { index: 8214 });
    v.insert("#anon_builtin-functions_20".to_string(), ContextId { index: 8114 });
    v.insert("#anon_interpolated-selectors_0".to_string(), ContextId { index: 8202 });
    v.insert("curly-braces".to_string(), ContextId { index: 8280 });
    v.insert("#anon_attr-function_2".to_string(), ContextId { index: 8100 });
    v.insert("#anon_custom-element-selectors_8".to_string(), ContextId { index: 8182 });
    v.insert("#anon_properties_5".to_string(), ContextId { index: 8230 });
    v.insert("#anon_selectors_7".to_string(), ContextId { index: 8253 });
    v.insert("#anon_custom-element-selectors_3".to_string(), ContextId { index: 8177 });
    v.insert("#anon_gradient-functions_2".to_string(), ContextId { index: 8196 });
    v.insert("#anon_builtin-functions_16".to_string(), ContextId { index: 8109 });
    v.insert("#anon_less-map-values_0".to_string(), ContextId { index: 8212 });
    v.insert("#anon_pseudo-classes_4".to_string(), ContextId { index: 8237 });
    v.insert("#anon_builtin-functions_26".to_string(), ContextId { index: 8120 });
    v.insert("#anon_media-query_0".to_string(), ContextId { index: 8222 });
    v.insert("color-values".to_string(), ContextId { index: 8275 });
    v.insert("filter-functions".to_string(), ContextId { index: 8284 });
    v.insert("image-type".to_string(), ContextId { index: 8291 });
    v.insert("#anon_at-rules_5".to_string(), ContextId { index: 8092 });
    v.insert("#anon_builtin-functions_38".to_string(), ContextId { index: 8133 });
    v.insert("#anon_filter-functions_0".to_string(), ContextId { index: 8186 });
    v.insert("resolution-type".to_string(), ContextId { index: 8321 });
    v.insert("#anon_builtin-functions_27".to_string(), ContextId { index: 8121 });
    v.insert("#anon_gradient-functions_0".to_string(), ContextId { index: 8194 });
    v.insert("__start".to_string(), ContextId { index: 8263 });
    v.insert("float-type".to_string(), ContextId { index: 8285 });
    v.insert("#anon_regexp-function_0".to_string(), ContextId { index: 8242 });
    v.insert("#anon_properties_2".to_string(), ContextId { index: 8227 });
    v.insert("vendor-prefix".to_string(), ContextId { index: 8331 });
    v.insert("pseudo-elements".to_string(), ContextId { index: 8318 });
    v.insert("#anon_custom-element-selectors_11".to_string(), ContextId { index: 8175 });
    v.insert("#anon_builtin-functions_21".to_string(), ContextId { index: 8115 });
    v.insert("interpolated-selectors".to_string(), ContextId { index: 8294 });
    v.insert("calc-function".to_string(), ContextId { index: 8271 });
    v.insert("#anon_pseudo-classes_2".to_string(), ContextId { index: 8235 });
    v.insert("#anon_selectors_8".to_string(), ContextId { index: 8254 });
    v.insert("#anon_builtin-functions_12".to_string(), ContextId { index: 8105 });
    v.insert("#anon_comment-line_0".to_string(), ContextId { index: 8169 });
    v.insert("url-prefix-function".to_string(), ContextId { index: 8329 });
    v.insert("media-query".to_string(), ContextId { index: 8308 });
    v.insert("angle-type".to_string(), ContextId { index: 8264 });
    v.insert("#anon_literal-string_1".to_string(), ContextId { index: 8221 });
    v.insert("#anon_at-supports-parens_0".to_string(), ContextId { index: 8097 });
    v.insert("color-adjuster-functions".to_string(), ContextId { index: 8272 });
    v.insert("at-supports-parens".to_string(), ContextId { index: 8268 });
    v.insert("#anon_builtin-functions_41".to_string(), ContextId { index: 8137 });
    v.insert("#anon_builtin-functions_31".to_string(), ContextId { index: 8126 });
    v.insert("#anon_color-functions_2".to_string(), ContextId { index: 8160 });
    v.insert("#anon_less-mixin-params_0".to_string(), ContextId { index: 8213 });
    v.insert("#anon_less-variables_3".to_string(), ContextId { index: 8217 });
    v.insert("#anon_builtin-functions_1".to_string(), ContextId { index: 8102 });
    v.insert("#anon_builtin-functions_25".to_string(), ContextId { index: 8119 });
    v.insert("gradient-functions".to_string(), ContextId { index: 8288 });
    v.insert("#anon_image-function_1".to_string(), ContextId { index: 8199 });
    v.insert("time-type".to_string(), ContextId { index: 8325 });
    v.insert("property-value-constants".to_string(), ContextId { index: 8314 });
    v.insert("property-values".to_string(), ContextId { index: 8316 });
    v.insert("number-type".to_string(), ContextId { index: 8310 });
    v.insert("#anon_properties_4".to_string(), ContextId { index: 8229 });
    v.insert("#anon_pseudo-classes_3".to_string(), ContextId { index: 8236 });
    v.insert("#anon_builtin-functions_37".to_string(), ContextId { index: 8132 });
    v.insert("domain-function".to_string(), ContextId { index: 8283 });
    v.insert("#anon_builtin-functions_43".to_string(), ContextId { index: 8139 });
    v.insert("#anon_color-functions_9".to_string(), ContextId { index: 8167 });
    v.insert("#anon_selectors_0".to_string(), ContextId { index: 8244 });
    v.insert("#anon_less-variables_2".to_string(), ContextId { index: 8216 });
    v.insert("#anon_builtin-functions_45".to_string(), ContextId { index: 8141 });
    v.insert("#anon_builtin-functions_2".to_string(), ContextId { index: 8113 });
    v.insert("#anon_gradient-functions_3".to_string(), ContextId { index: 8197 });
    v.insert("#anon_line-names_0".to_string(), ContextId { index: 8219 });
    v.insert("#anon_color-adjuster-functions_4".to_string(), ContextId { index: 8152 });
    v.insert("#anon_selectors_5".to_string(), ContextId { index: 8251 });
    v.insert("string-content".to_string(), ContextId { index: 8324 });
    v.insert("#anon_domain-function_1".to_string(), ContextId { index: 8185 });
    v.insert("#anon_builtin-functions_24".to_string(), ContextId { index: 8118 });
    v.insert("#anon_filter-functions_1".to_string(), ContextId { index: 8187 });
    v.insert("image-set-function".to_string(), ContextId { index: 8290 });
    v.insert("unquoted-string".to_string(), ContextId { index: 8327 });
    v.insert("#anon_filter-functions_4".to_string(), ContextId { index: 8190 });
    v.insert("cross-fade-function".to_string(), ContextId { index: 8279 });
    v.insert("#anon_properties_1".to_string(), ContextId { index: 8226 });
    v.insert("#anon_builtin-functions_39".to_string(), ContextId { index: 8134 });
    v.insert("#anon_at-rules_7".to_string(), ContextId { index: 8094 });
    v.insert("#anon_filter-functions_7".to_string(), ContextId { index: 8193 });
    v.insert("#anon_selectors_1".to_string(), ContextId { index: 8245 });
    v.insert("#anon_properties_3".to_string(), ContextId { index: 8228 });
    v.insert("inside-calc-parens".to_string(), ContextId { index: 8292 });
    v.insert("custom-property-name".to_string(), ContextId { index: 8282 });
    v.insert("less-map-lookups".to_string(), ContextId { index: 8300 });
    v.insert("color-functions".to_string(), ContextId { index: 8274 });
    v.insert("#anon_builtin-functions_9".to_string(), ContextId { index: 8146 });
    v.insert("#anon_less-aliases_3".to_string(), ContextId { index: 8210 });
    v.insert("#anon_less-aliases_0".to_string(), ContextId { index: 8207 });
    v.insert("qualified-name".to_string(), ContextId { index: 8319 });
    v.insert("#anon_minmax-function_1".to_string(), ContextId { index: 8224 });
    v.insert("#anon_url-prefix-function_0".to_string(), ContextId { index: 8258 });
    v.insert("integer-type".to_string(), ContextId { index: 8293 });
    v.insert("#anon_at-rules_2".to_string(), ContextId { index: 8089 });
    v.insert("#anon_builtin-functions_14".to_string(), ContextId { index: 8107 });
    v.insert("#anon_builtin-functions_23".to_string(), ContextId { index: 8117 });
    v.insert("#anon_builtin-functions_8".to_string(), ContextId { index: 8145 });
    v.insert("#anon_color-adjuster-functions_8".to_string(), ContextId { index: 8156 });
    v.insert("#anon_selectors_4".to_string(), ContextId { index: 8250 });
    v.insert("#anon_interpolated-selectors_4".to_string(), ContextId { index: 8206 });
    v.insert("#anon_pseudo-classes_7".to_string(), ContextId { index: 8240 });
    v.insert("#anon_color-functions_1".to_string(), ContextId { index: 8159 });
    v.insert("#anon_url-function_0".to_string(), ContextId { index: 8256 });
    v.insert("#anon_builtin-functions_19".to_string(), ContextId { index: 8112 });
    v.insert("#anon_at-rules_3".to_string(), ContextId { index: 8090 });
    v.insert("#anon_less-variables_1".to_string(), ContextId { index: 8215 });
    v.insert("#anon_at-rules_10".to_string(), ContextId { index: 8087 });
    v.insert("#anon_at-rules_6".to_string(), ContextId { index: 8093 });
    v.insert("#anon_filter-functions_3".to_string(), ContextId { index: 8189 });
    v.insert("#anon_custom-element-selectors_9".to_string(), ContextId { index: 8183 });
    v.insert("comment-block".to_string(), ContextId { index: 8277 });
    v.insert("#anon_image-set-function_1".to_string(), ContextId { index: 8201 });
    v.insert("#anon_filter-functions_5".to_string(), ContextId { index: 8191 });
    v.insert("#anon_pseudo-classes_0".to_string(), ContextId { index: 8233 });
    v.insert("numeric-values".to_string(), ContextId { index: 8311 });
    v.insert("regexp-function".to_string(), ContextId { index: 8320 });
    v.insert("#anon_builtin-functions_10".to_string(), ContextId { index: 8103 });
    v.insert("#anon_less-aliases_2".to_string(), ContextId { index: 8209 });
    v.insert("#anon_color-functions_5".to_string(), ContextId { index: 8163 });
    v.insert("#anon_less-functions_0".to_string(), ContextId { index: 8211 });
    v.insert("less-variables".to_string(), ContextId { index: 8304 });
    v.insert("#anon_color-adjuster-functions_0".to_string(), ContextId { index: 8148 });
    v.insert("#anon_properties_0".to_string(), ContextId { index: 8225 });
    v.insert("#anon_selectors_2".to_string(), ContextId { index: 8248 });
    v.insert("#anon_builtin-functions_15".to_string(), ContextId { index: 8108 });
    v.insert("#anon_calc-function_0".to_string(), ContextId { index: 8147 });
    v.insert("comment-line".to_string(), ContextId { index: 8278 });
    v.insert("custom-element-selectors".to_string(), ContextId { index: 8281 });
    v.insert("pseudo-classes".to_string(), ContextId { index: 8317 });
    v.insert("#anon_cross-fade-function_0".to_string(), ContextId { index: 8170 });
    v.insert("properties".to_string(), ContextId { index: 8313 });
    v.insert("#anon_builtin-functions_17".to_string(), ContextId { index: 8110 });
    v.insert("#anon_color-adjuster-functions_2".to_string(), ContextId { index: 8150 });
    v.insert("less-functions".to_string(), ContextId { index: 8298 });
    v.insert("#anon_literal-string_0".to_string(), ContextId { index: 8220 });
    v.insert("#anon_color-adjuster-functions_7".to_string(), ContextId { index: 8155 });
    v.insert("#anon_color-functions_3".to_string(), ContextId { index: 8161 });
    v.insert("comma-delimiter".to_string(), ContextId { index: 8276 });
    v.insert("#anon_color-functions_6".to_string(), ContextId { index: 8164 });
    v.insert("#anon_color-adjuster-functions_3".to_string(), ContextId { index: 8151 });
    v.insert("#anon_custom-element-selectors_6".to_string(), ContextId { index: 8180 });
    v.insert("#anon_comment-block_0".to_string(), ContextId { index: 8168 });
    v.insert("#anon_interpolated-selectors_2".to_string(), ContextId { index: 8204 });
    v.insert("#anon_selectors_10".to_string(), ContextId { index: 8246 });
    v.insert("#anon_custom-element-selectors_7".to_string(), ContextId { index: 8181 });
    v.insert("selector-parts".to_string(), ContextId { index: 8322 });
    v.insert("#anon_builtin-functions_11".to_string(), ContextId { index: 8104 });
    v.insert("#anon_builtin-functions_28".to_string(), ContextId { index: 8122 });
    v.insert("#anon_builtin-functions_42".to_string(), ContextId { index: 8138 });
    v.insert("#anon_pseudo-classes_5".to_string(), ContextId { index: 8238 });
    v.insert("minmax-function".to_string(), ContextId { index: 8309 });
    v.insert("#anon_at-rules_4".to_string(), ContextId { index: 8091 });
    v.insert("#anon_selectors_11".to_string(), ContextId { index: 8247 });
    v.insert("#anon_builtin-functions_29".to_string(), ContextId { index: 8123 });
    v.insert("#anon_at-rules_1".to_string(), ContextId { index: 8086 });
    v.insert("#anon_interpolated-selectors_3".to_string(), ContextId { index: 8205 });
    v.insert("#anon_color-functions_8".to_string(), ContextId { index: 8166 });
    v.insert("#anon_color-adjuster-functions_6".to_string(), ContextId { index: 8154 });
    v.insert("#anon_custom-element-selectors_4".to_string(), ContextId { index: 8178 });
    v.insert("#anon_gradient-functions_1".to_string(), ContextId { index: 8195 });
    v.insert("#anon_properties_6".to_string(), ContextId { index: 8231 });
    v.insert("#anon_selectors_9".to_string(), ContextId { index: 8255 });
    v.insert("#anon_url-prefix-function_1".to_string(), ContextId { index: 8259 });
    v.insert("#anon_builtin-functions_18".to_string(), ContextId { index: 8111 });
    v.insert("function-notation-terminator".to_string(), ContextId { index: 8287 });
    v.insert("#anon_at-rules_11".to_string(), ContextId { index: 8088 });
    v.insert("#anon_color-adjuster-functions_5".to_string(), ContextId { index: 8153 });
    v.insert("#anon_image-set-function_0".to_string(), ContextId { index: 8200 });
    v.insert("less-mixin-params".to_string(), ContextId { index: 8302 });
    v.insert("frequency-type".to_string(), ContextId { index: 8286 });
    v.insert("#anon_attr-function_0".to_string(), ContextId { index: 8098 });
    v.insert("#anon_custom-element-selectors_5".to_string(), ContextId { index: 8179 });
    v.insert("#anon_less-variables_4".to_string(), ContextId { index: 8218 });
    v.insert("#anon_regexp-function_1".to_string(), ContextId { index: 8243 });
    v.insert("#anon_custom-element-selectors_1".to_string(), ContextId { index: 8173 });
    v.insert("#anon_pseudo-classes_1".to_string(), ContextId { index: 8234 });
    v.insert("#anon_pseudo-classes_6".to_string(), ContextId { index: 8239 });
    v.insert("at-rules".to_string(), ContextId { index: 8266 });
    v.insert("#anon_builtin-functions_4".to_string(), ContextId { index: 8135 });
    v.insert("#anon_domain-function_0".to_string(), ContextId { index: 8184 });
    v.insert("less-operators".to_string(), ContextId { index: 8303 });
    v.insert("#anon_builtin-functions_3".to_string(), ContextId { index: 8124 });
    v.insert("#anon_builtin-functions_22".to_string(), ContextId { index: 8116 });
    v.insert("#anon_pseudo-classes_8".to_string(), ContextId { index: 8241 });
    v.insert("var-function".to_string(), ContextId { index: 8330 });
    v
  }
} }