
#![allow(unused_imports)]
#![allow(dead_code)]

use jirs_syntect::{*, parsing::*};
use lazycell::AtomicLazyCell;

#[inline(always)]
pub fn load() -> SyntaxReference {
        SyntaxReference {  name: "Sass".to_string(),
  file_extensions: vec!["sass".to_string()],
  scope: Scope { a: 845030520520704, b: 0 },
  first_line_match: None,
  hidden: false,
  variables: {
    let mut v = std::collections::HashMap::new();
    v.insert("escape".to_string(), "(?:{{unicode}}|\\\\[^\\n\\f\\h])".to_string());
    v.insert("unicode".to_string(), "\\\\\\h{1,6}[ \\t\\n\\f]?".to_string());
    v.insert("viewport_percentage_lengths".to_string(), "(?i:vw|vh|vmin|vmax)".to_string());
    v.insert("absolute_lengths".to_string(), "(?i:cm|mm|q|in|pt|pc|px|fr)".to_string());
    v.insert("angle_units".to_string(), "(?i:deg|grad|rad|turn)".to_string());
    v.insert("nmchar".to_string(), "(?:[[-\\w]{{nonascii}}]|{{escape}})".to_string());
    v.insert("float".to_string(), "(?x:\n  [-+]? \\d* (\\.) \\d+ {{exponent}}?\n| [-+]? \\d+          {{exponent}}\n)".to_string());
    v.insert("custom_elements".to_string(), "\\b([a-z](?:{{custom_element_chars}})*-(?:{{custom_element_chars}})*)\\b(?!{{ident}})".to_string());
    v.insert("duration_units".to_string(), "(?i:s|ms)".to_string());
    v.insert("ident".to_string(), "(?:--{{nmchar}}+|-?{{nmstart}}{{nmchar}}*)".to_string());
    v.insert("nmstart".to_string(), "(?:[[_a-zA-Z]{{nonascii}}]|{{escape}})".to_string());
    v.insert("exponent".to_string(), "(?:[eE]{{integer}})".to_string());
    v.insert("nonascii".to_string(), "[\\p{L}\\p{M}\\p{S}\\p{N}&&[[:^ascii:]]]".to_string());
    v.insert("combinators".to_string(), "(?:>{1,3}|[~+])".to_string());
    v.insert("custom_element_chars".to_string(), "(?x:\n    [-_a-z0-9\\x{00B7}]\n  | \\\\\\.\n  | [\\x{00C0}-\\x{00D6}]\n  | [\\x{00D8}-\\x{00F6}]\n  | [\\x{00F8}-\\x{02FF}]\n  | [\\x{0300}-\\x{037D}]\n  | [\\x{037F}-\\x{1FFF}]\n  | [\\x{200C}-\\x{200D}]\n  | [\\x{203F}-\\x{2040}]\n  | [\\x{2070}-\\x{218F}]\n  | [\\x{2C00}-\\x{2FEF}]\n  | [\\x{3001}-\\x{D7FF}]\n  | [\\x{F900}-\\x{FDCF}]\n  | [\\x{FDF0}-\\x{FFFD}]\n  | [\\x{10000}-\\x{EFFFF}]\n)".to_string());
    v.insert("counter_styles".to_string(), "(?xi:\n    arabic-indic | armenian | bengali | cambodian | circle\n  | cjk-decimal | cjk-earthly-branch | cjk-heavenly-stem | decimal-leading-zero\n  | decimal | devanagari | disclosure-closed | disclosure-open | disc\n  | ethiopic-numeric | georgian | gujarati | gurmukhi | hebrew\n  | hiragana-iroha | hiragana | japanese-formal | japanese-informal\n  | kannada | katakana-iroha | katakana | khmer\n  | korean-hangul-formal | korean-hanja-formal | korean-hanja-informal | lao\n  | lower-alpha | lower-armenian | lower-greek | lower-latin | lower-roman\n  | malayalam | mongolian | myanmar | oriya | persian\n  | simp-chinese-formal | simp-chinese-informal\n  | square | tamil | telugu | thai | tibetan\n  | trad-chinese-formal | trad-chinese-informal\n  | upper-alpha | upper-armenian | upper-latin | upper-roman\n)".to_string());
    v.insert("font_relative_lengths".to_string(), "(?i:em|ex|ch|rem)".to_string());
    v.insert("integer".to_string(), "(?:[-+]?\\d+)".to_string());
    v.insert("property_names".to_string(), "\\b(?x)(\n    display|width|background-color|height|position|font-family|font-weight\n  | top|opacity|cursor|background-image|right|visibility|box-sizing\n  | user-select|left|float|margin-left|margin-top|line-height\n  | padding-left|z-index|margin-bottom|margin-right|margin\n  | vertical-align|padding-top|white-space|border-radius|padding-bottom\n  | padding-right|padding|bottom|clear|max-width|box-shadow|content\n  | border-color|min-height|min-width|font-style|border-width\n  | border-collapse|background-size|text-overflow|max-height|text-transform\n  | text-shadow|text-indent|border-style|overflow-y|list-style-type\n  | word-wrap|border-spacing|appearance|zoom|overflow-x|border-top-left-radius\n  | border-bottom-left-radius|border-top-color|pointer-events\n  | border-bottom-color|align-items|justify-content|letter-spacing\n  | border-top-right-radius|border-bottom-right-radius|border-right-width\n  | font-smoothing|border-bottom-width|border-right-color|direction\n  | border-top-width|src|border-left-color|border-left-width\n  | tap-highlight-color|table-layout|background-clip|word-break\n  | transform-origin|resize|filter|backdrop-filter|backface-visibility|text-rendering\n  | box-orient|transition-property|transition-duration|word-spacing\n  | quotes|outline-offset|animation-timing-function|animation-duration\n  | animation-name|transition-timing-function|border-bottom-style\n  | border-bottom|transition-delay|transition|unicode-bidi|border-top-style\n  | border-top|unicode-range|list-style-position|orphans|outline-width\n  | line-clamp|order|flex-direction|box-pack|animation-fill-mode\n  | outline-color|list-style-image|list-style|touch-action|flex-grow\n  | border-left-style|border-left|animation-iteration-count\n  | page-break-inside|box-flex|box-align|page-break-after|animation-delay\n  | widows|border-right-style|border-right|flex-align|outline-style\n  | outline|background-origin|animation-direction|fill-opacity\n  | background-attachment|flex-wrap|transform-style|counter-increment\n  | overflow-wrap|counter-reset|animation-play-state|animation\n  | will-change|box-ordinal-group|image-rendering|mask-image|flex-flow\n  | background-position-y|stroke-width|background-position-x|background-position\n  | background-blend-mode|flex-shrink|flex-basis|flex-order|flex-item-align\n  | flex-line-pack|flex-negative|flex-pack|flex-positive|flex-preferred-size\n  | flex|user-drag|font-stretch|column-count|empty-cells|align-self\n  | caption-side|mask-size|column-gap|mask-repeat|box-direction\n  | font-feature-settings|mask-position|align-content|object-fit\n  | columns|text-fill-color|clip-path|stop-color|font-kerning\n  | page-break-before|stroke-dasharray|size|fill-rule|border-image-slice\n  | column-width|break-inside|column-break-before|border-image-width\n  | stroke-dashoffset|border-image-repeat|border-image-outset|line-break\n  | stroke-linejoin|stroke-linecap|stroke-miterlimit|stroke-opacity\n  | stroke|shape-rendering|border-image-source|border-image|border\n  | tab-size|writing-mode|perspective-origin-y|perspective-origin-x\n  | perspective-origin|perspective|text-align-last|text-align|clip-rule\n  | clip|text-anchor|column-rule-color|box-decoration-break|column-fill\n  | fill|column-rule-style|mix-blend-mode|text-emphasis-color\n  | baseline-shift|dominant-baseline|page|alignment-baseline\n  | column-rule-width|column-rule|break-after|font-variant-ligatures\n  | transform-origin-y|transform-origin-x|transform|object-position\n  | break-before|column-span|isolation|shape-outside|all\n  | color-interpolation-filters|marker|marker-end|marker-start\n  | marker-mid|color-rendering|color-interpolation|background-repeat-x\n  | background-repeat-y|background-repeat|background|mask-type\n  | flood-color|flood-opacity|text-orientation|mask-composite\n  | text-emphasis-style|paint-order|lighting-color|shape-margin\n  | text-emphasis-position|text-emphasis|shape-image-threshold\n  | mask-clip|mask-origin|mask|font-variant-caps|font-variant-alternates\n  | font-variant-east-asian|font-variant-numeric|font-variant-position\n  | font-variant|font-size-adjust|font-size|font-language-override\n  | font-display|font-synthesis|font|line-box-contain|text-justify\n  | text-decoration-color|text-decoration-style|text-decoration-line\n  | text-decoration|text-underline-position|grid-template-rows\n  | grid-template-columns|grid-template-areas|grid-template|rotate|scale\n  | translate|scroll-behavior|grid-column-start|grid-column-end\n  | grid-column-gap|grid-row-start|grid-row-end|grid-auto-rows\n  | grid-area|grid-auto-flow|grid-auto-columns|image-orientation\n  | hyphens|overflow-scrolling|overflow|color-profile|kerning\n  | nbsp-mode|color|image-resolution|grid-row-gap|grid-row|grid-column\n  | blend-mode|azimuth|pause-after|pause-before|pause|pitch-range|pitch\n  | text-height|system|negative|prefix|suffix|range|pad|fallback\n  | additive-symbols|symbols|speak-as|speak|grid-gap\n)\\b".to_string());
    v.insert("frequency_units".to_string(), "(?i:Hz|kHz)".to_string());
    v.insert("pseudo_elements".to_string(), "(?x:\n    (:{1,2})(?:before|after|first-line|first-letter) # CSS1 & CSS2 require : or ::\n  | (::)(-(?:moz|ms|webkit)-)?(?:{{ident}}) # CSS3 requires ::\n)\\b".to_string());
    v.insert("element_names".to_string(), "\\b(a|abbr|acronym|address|applet|area|article|aside|audio|b|base|basefont|bdi|bdo|big|blockquote|body|br|button|canvas|caption|cite|code|col|colgroup|content|data|datalist|dd|del|details|dfn|dir|dialog|div|dl|dt|element|em|embed|eventsource|fieldset|figure|figcaption|footer|form|frame|frameset|h[1-6]|head|header|hgroup|hr|html|i|iframe|img|input|ins|isindex|kbd|keygen|label|legend|li|link|main|map|mark|menu|meta|meter|nav|noframes|noscript|object|ol|optgroup|option|output|p|param|picture|pre|progress|q|rp|rt|rtc|s|samp|script|section|select|shadow|small|source|span|strike|strong|style|sub|summary|sup|svg|table|tbody|td|template|textarea|tfoot|th|thead|time|title|tr|track|tt|u|ul|var|video|wbr|xmp|circle|clipPath|defs|ellipse|filter|foreignObject|g|glyph|glyphRef|image|line|linearGradient|marker|mask|path|pattern|polygon|polyline|radialGradient|rect|stop|switch|symbol|text|textPath|tref|tspan|use)\\b".to_string());
    v.insert("regular_pseudo_classes".to_string(), "\\b(active|any-link|blank|checked|current|default|defined|disabled|drop|empty|enabled|first|first-child|first-of-type|fullscreen|future|focus|focus-visible|focus-within|host|hover|indeterminate|in-range|invalid|last-child|last-of-type|left|link|local-link|only-child|only-of-type|optional|out-of-range|past|placeholder-shown|read-only|read-write|required|right|root|scope|target|target-within|user-invalid|valid|visited)\\b(?![-])".to_string());
    v.insert("functional_pseudo_classes".to_string(), "\\b(dir|lang|matches|not|has|drop|nth-last-child|nth-child|nth-last-of-type|nth-of-type)\\b".to_string());
    v.insert("resolution_units".to_string(), "(?i:dpi|dpcm|dppx)".to_string());
    v
  },
  contexts: {
    let mut v = std::collections::HashMap::new();
    v.insert("sass-variables".to_string(), ContextId { index: 9149 });
    v.insert("#anon_color-adjuster-functions_0".to_string(), ContextId { index: 8972 });
    v.insert("#anon_color-adjuster-functions_6".to_string(), ContextId { index: 8978 });
    v.insert("#anon_attr-function_0".to_string(), ContextId { index: 8922 });
    v.insert("#anon_literal-string_1".to_string(), ContextId { index: 9031 });
    v.insert("#anon_selectors_4".to_string(), ContextId { index: 9073 });
    v.insert("#anon_builtin-functions_17".to_string(), ContextId { index: 8934 });
    v.insert("at-supports-operators".to_string(), ContextId { index: 9089 });
    v.insert("cross-fade-function".to_string(), ContextId { index: 9102 });
    v.insert("#anon_var-function_0".to_string(), ContextId { index: 9083 });
    v.insert("gradient-functions".to_string(), ContextId { index: 9112 });
    v.insert("#anon_selectors_12".to_string(), ContextId { index: 9069 });
    v.insert("#anon_sass-mixin-directives_1".to_string(), ContextId { index: 9064 });
    v.insert("#anon_builtin-functions_5".to_string(), ContextId { index: 8966 });
    v.insert("#anon_color-functions_6".to_string(), ContextId { index: 8988 });
    v.insert("#anon_interpolated-selectors_3".to_string(), ContextId { index: 9027 });
    v.insert("#anon_at-rules_10".to_string(), ContextId { index: 8895 });
    v.insert("#anon_color-adjuster-functions_4".to_string(), ContextId { index: 8976 });
    v.insert("#anon_at-rules_9".to_string(), ContextId { index: 8920 });
    v.insert("builtin-functions".to_string(), ContextId { index: 9092 });
    v.insert("#anon_selectors_1".to_string(), ContextId { index: 9066 });
    v.insert("domain-function".to_string(), ContextId { index: 9105 });
    v.insert("#anon_interpolated-selector-body_0".to_string(), ContextId { index: 9023 });
    v.insert("percentage-type".to_string(), ContextId { index: 9129 });
    v.insert("#anon_builtin-functions_16".to_string(), ContextId { index: 8933 });
    v.insert("#anon_builtin-functions_22".to_string(), ContextId { index: 8940 });
    v.insert("sass-value-expression".to_string(), ContextId { index: 9148 });
    v.insert("at-rules".to_string(), ContextId { index: 9088 });
    v.insert("#anon_builtin-functions_45".to_string(), ContextId { index: 8965 });
    v.insert("#anon_pseudo-classes_5".to_string(), ContextId { index: 9050 });
    v.insert("#anon_selectors_9".to_string(), ContextId { index: 9078 });
    v.insert("#anon_at-rules_2".to_string(), ContextId { index: 8905 });
    v.insert("#anon_color-adjuster-functions_8".to_string(), ContextId { index: 8980 });
    v.insert("#anon_at-rules_18".to_string(), ContextId { index: 8903 });
    v.insert("unquoted-string".to_string(), ContextId { index: 9156 });
    v.insert("#anon_interpolated-selectors_1".to_string(), ContextId { index: 9025 });
    v.insert("function-arguments".to_string(), ContextId { index: 9110 });
    v.insert("#anon_filter-functions_7".to_string(), ContextId { index: 9010 });
    v.insert("custom-property-name".to_string(), ContextId { index: 9104 });
    v.insert("#anon_builtin-functions_2".to_string(), ContextId { index: 8937 });
    v.insert("#anon_builtin-functions_18".to_string(), ContextId { index: 8935 });
    v.insert("#anon_at-rules_24".to_string(), ContextId { index: 8910 });
    v.insert("image-function".to_string(), ContextId { index: 9113 });
    v.insert("#anon_function-arguments_0".to_string(), ContextId { index: 9013 });
    v.insert("#anon_builtin-functions_4".to_string(), ContextId { index: 8959 });
    v.insert("#anon_pseudo-classes_1".to_string(), ContextId { index: 9046 });
    v.insert("time-type".to_string(), ContextId { index: 9153 });
    v.insert("#anon_builtin-functions_43".to_string(), ContextId { index: 8963 });
    v.insert("#anon_at-rules_3".to_string(), ContextId { index: 8914 });
    v.insert("#anon_domain-function_1".to_string(), ContextId { index: 9002 });
    v.insert("#anon_at-rules_7".to_string(), ContextId { index: 8918 });
    v.insert("#anon_comment-block_0".to_string(), ContextId { index: 8992 });
    v.insert("#anon_builtin-functions_6".to_string(), ContextId { index: 8967 });
    v.insert("color-adjuster-functions".to_string(), ContextId { index: 9094 });
    v.insert("sass-mixin-directives".to_string(), ContextId { index: 9145 });
    v.insert("calc-function".to_string(), ContextId { index: 9093 });
    v.insert("line-names".to_string(), ContextId { index: 9122 });
    v.insert("#anon_sass-maps_0".to_string(), ContextId { index: 9059 });
    v.insert("#anon_line-names_0".to_string(), ContextId { index: 9029 });
    v.insert("#anon_builtin-functions_1".to_string(), ContextId { index: 8926 });
    v.insert("frequency-type".to_string(), ContextId { index: 9108 });
    v.insert("at-supports-parens".to_string(), ContextId { index: 9090 });
    v.insert("#anon_at-rules_1".to_string(), ContextId { index: 8894 });
    v.insert("#anon_selectors_3".to_string(), ContextId { index: 9072 });
    v.insert("#anon_at-supports-parens_0".to_string(), ContextId { index: 8921 });
    v.insert("inside-calc-parens".to_string(), ContextId { index: 9116 });
    v.insert("#anon_builtin-functions_31".to_string(), ContextId { index: 8950 });
    v.insert("#anon_filter-functions_6".to_string(), ContextId { index: 9009 });
    v.insert("length-type".to_string(), ContextId { index: 9121 });
    v.insert("sass-maps".to_string(), ContextId { index: 9142 });
    v.insert("#anon_sass-mixin-directives_0".to_string(), ContextId { index: 9063 });
    v.insert("#anon_builtin-functions_33".to_string(), ContextId { index: 8952 });
    v.insert("angle-type".to_string(), ContextId { index: 9087 });
    v.insert("var-function".to_string(), ContextId { index: 9159 });
    v.insert("media-query".to_string(), ContextId { index: 9125 });
    v.insert("#anon_image-function_1".to_string(), ContextId { index: 9020 });
    v.insert("attr-function".to_string(), ContextId { index: 9091 });
    v.insert("color-functions".to_string(), ContextId { index: 9096 });
    v.insert("#anon_selectors_10".to_string(), ContextId { index: 9067 });
    v.insert("#anon_at-rules_15".to_string(), ContextId { index: 8900 });
    v.insert("comment-line".to_string(), ContextId { index: 9101 });
    v.insert("#anon_builtin-functions_44".to_string(), ContextId { index: 8964 });
    v.insert("#anon_at-rules_14".to_string(), ContextId { index: 8899 });
    v.insert("comment-block".to_string(), ContextId { index: 9100 });
    v.insert("#anon_filter-functions_4".to_string(), ContextId { index: 9007 });
    v.insert("filter-functions".to_string(), ContextId { index: 9106 });
    v.insert("#anon_at-rules_12".to_string(), ContextId { index: 8897 });
    v.insert("#anon_builtin-functions_28".to_string(), ContextId { index: 8946 });
    v.insert("unquoted-concatenated-string".to_string(), ContextId { index: 9155 });
    v.insert("#anon_builtin-functions_29".to_string(), ContextId { index: 8947 });
    v.insert("#anon_cross-fade-function_1".to_string(), ContextId { index: 8995 });
    v.insert("#anon_at-rules_21".to_string(), ContextId { index: 8907 });
    v.insert("#anon_builtin-functions_40".to_string(), ContextId { index: 8960 });
    v.insert("#anon_selectors_6".to_string(), ContextId { index: 9075 });
    v.insert("#anon_color-adjuster-functions_9".to_string(), ContextId { index: 8981 });
    v.insert("#anon_color-functions_7".to_string(), ContextId { index: 8989 });
    v.insert("#anon_at-rules_27".to_string(), ContextId { index: 8913 });
    v.insert("#anon_builtin-functions_26".to_string(), ContextId { index: 8944 });
    v.insert("#anon_builtin-functions_39".to_string(), ContextId { index: 8958 });
    v.insert("#anon_properties_8".to_string(), ContextId { index: 9043 });
    v.insert("__main".to_string(), ContextId { index: 9085 });
    v.insert("#anon_media-query_0".to_string(), ContextId { index: 9032 });
    v.insert("#anon_sass-functions_0".to_string(), ContextId { index: 9057 });
    v.insert("#anon_properties_6".to_string(), ContextId { index: 9041 });
    v.insert("sass-operators".to_string(), ContextId { index: 9146 });
    v.insert("url-function".to_string(), ContextId { index: 9157 });
    v.insert("vendor-prefix".to_string(), ContextId { index: 9160 });
    v.insert("#anon_at-rules_17".to_string(), ContextId { index: 8902 });
    v.insert("#anon_url-function_1".to_string(), ContextId { index: 9080 });
    v.insert("#anon_var-function_1".to_string(), ContextId { index: 9084 });
    v.insert("#anon_function-arguments_1".to_string(), ContextId { index: 9014 });
    v.insert("#anon_at-rules_16".to_string(), ContextId { index: 8901 });
    v.insert("#anon_at-rules_19".to_string(), ContextId { index: 8904 });
    v.insert("#anon_minmax-function_0".to_string(), ContextId { index: 9033 });
    v.insert("function-notation-terminator".to_string(), ContextId { index: 9111 });
    v.insert("#anon_selectors_8".to_string(), ContextId { index: 9077 });
    v.insert("#anon_url-function_0".to_string(), ContextId { index: 9079 });
    v.insert("minmax-function".to_string(), ContextId { index: 9126 });
    v.insert("sass-interpolation".to_string(), ContextId { index: 9141 });
    v.insert("property-value-wrapper".to_string(), ContextId { index: 9132 });
    v.insert("#anon_properties_0".to_string(), ContextId { index: 9035 });
    v.insert("#anon_builtin-functions_14".to_string(), ContextId { index: 8931 });
    v.insert("#anon_builtin-functions_37".to_string(), ContextId { index: 8956 });
    v.insert("#anon_filter-functions_3".to_string(), ContextId { index: 9006 });
    v.insert("#anon_color-functions_1".to_string(), ContextId { index: 8983 });
    v.insert("#anon_pseudo-classes_8".to_string(), ContextId { index: 9053 });
    v.insert("#anon_selectors_11".to_string(), ContextId { index: 9068 });
    v.insert("#anon_builtin-functions_21".to_string(), ContextId { index: 8939 });
    v.insert("#anon_builtin-functions_9".to_string(), ContextId { index: 8970 });
    v.insert("#anon_builtin-functions_30".to_string(), ContextId { index: 8949 });
    v.insert("properties".to_string(), ContextId { index: 9130 });
    v.insert("#anon_url-prefix-function_1".to_string(), ContextId { index: 9082 });
    v.insert("sass-functions".to_string(), ContextId { index: 9140 });
    v.insert("#anon_calc-function_0".to_string(), ContextId { index: 8971 });
    v.insert("#anon_gradient-functions_1".to_string(), ContextId { index: 9016 });
    v.insert("interpolated-selectors".to_string(), ContextId { index: 9119 });
    v.insert("#anon_color-functions_9".to_string(), ContextId { index: 8991 });
    v.insert("regexp-function".to_string(), ContextId { index: 9137 });
    v.insert("#anon_properties_2".to_string(), ContextId { index: 9037 });
    v.insert("url-prefix-function".to_string(), ContextId { index: 9158 });
    v.insert("#anon_builtin-functions_42".to_string(), ContextId { index: 8962 });
    v.insert("#anon_properties_5".to_string(), ContextId { index: 9040 });
    v.insert("#anon_frontmatter_1".to_string(), ContextId { index: 9012 });
    v.insert("image-set-function".to_string(), ContextId { index: 9114 });
    v.insert("#anon_color-functions_3".to_string(), ContextId { index: 8985 });
    v.insert("#anon_frontmatter_0".to_string(), ContextId { index: 9011 });
    v.insert("#anon_properties_4".to_string(), ContextId { index: 9039 });
    v.insert("#anon_filter-functions_5".to_string(), ContextId { index: 9008 });
    v.insert("sass-script-expression".to_string(), ContextId { index: 9147 });
    v.insert("#anon_builtin-functions_10".to_string(), ContextId { index: 8927 });
    v.insert("pseudo-classes".to_string(), ContextId { index: 9134 });
    v.insert("color-hex-values".to_string(), ContextId { index: 9097 });
    v.insert("#anon_at-rules_25".to_string(), ContextId { index: 8911 });
    v.insert("#anon_builtin-functions_19".to_string(), ContextId { index: 8936 });
    v.insert("#anon_custom-element-selectors_2".to_string(), ContextId { index: 8998 });
    v.insert("custom-element-selectors".to_string(), ContextId { index: 9103 });
    v.insert("float-type".to_string(), ContextId { index: 9107 });
    v.insert("#anon_builtin-functions_35".to_string(), ContextId { index: 8954 });
    v.insert("#anon_pseudo-classes_3".to_string(), ContextId { index: 9048 });
    v.insert("#anon_builtin-functions_27".to_string(), ContextId { index: 8945 });
    v.insert("qualified-name".to_string(), ContextId { index: 9136 });
    v.insert("#anon_url-prefix-function_0".to_string(), ContextId { index: 9081 });
    v.insert("#anon_at-rules_6".to_string(), ContextId { index: 8917 });
    v.insert("#anon_gradient-functions_2".to_string(), ContextId { index: 9017 });
    v.insert("selectors".to_string(), ContextId { index: 9151 });
    v.insert("#anon_interpolated-selectors_4".to_string(), ContextId { index: 9028 });
    v.insert("#anon_selectors_7".to_string(), ContextId { index: 9076 });
    v.insert("number-type".to_string(), ContextId { index: 9127 });
    v.insert("#anon_color-adjuster-functions_3".to_string(), ContextId { index: 8975 });
    v.insert("unicode-range".to_string(), ContextId { index: 9154 });
    v.insert("#anon_filter-functions_0".to_string(), ContextId { index: 9003 });
    v.insert("main".to_string(), ContextId { index: 9124 });
    v.insert("sass-mixin-call".to_string(), ContextId { index: 9143 });
    v.insert("#anon_color-functions_5".to_string(), ContextId { index: 8987 });
    v.insert("#anon_gradient-functions_0".to_string(), ContextId { index: 9015 });
    v.insert("#anon_image-set-function_0".to_string(), ContextId { index: 9021 });
    v.insert("#anon_builtin-functions_15".to_string(), ContextId { index: 8932 });
    v.insert("#anon_builtin-functions_0".to_string(), ContextId { index: 8925 });
    v.insert("#anon_builtin-functions_36".to_string(), ContextId { index: 8955 });
    v.insert("#anon_builtin-functions_11".to_string(), ContextId { index: 8928 });
    v.insert("#anon_builtin-functions_8".to_string(), ContextId { index: 8969 });
    v.insert("#anon_sass-mixin-call_0".to_string(), ContextId { index: 9060 });
    v.insert("#anon_property-value-wrapper_0".to_string(), ContextId { index: 9044 });
    v.insert("#anon_attr-function_1".to_string(), ContextId { index: 8923 });
    v.insert("#anon_at-rules_4".to_string(), ContextId { index: 8915 });
    v.insert("selector-parts".to_string(), ContextId { index: 9150 });
    v.insert("#anon_literal-string_0".to_string(), ContextId { index: 9030 });
    v.insert("literal-string".to_string(), ContextId { index: 9123 });
    v.insert("sass-mixin-def".to_string(), ContextId { index: 9144 });
    v.insert("#anon_interpolated-selectors_0".to_string(), ContextId { index: 9024 });
    v.insert("integer-type".to_string(), ContextId { index: 9117 });
    v.insert("property-value-constants".to_string(), ContextId { index: 9131 });
    v.insert("#anon_builtin-functions_13".to_string(), ContextId { index: 8930 });
    v.insert("#anon_image-set-function_1".to_string(), ContextId { index: 9022 });
    v.insert("__start".to_string(), ContextId { index: 9086 });
    v.insert("keyframe-operators".to_string(), ContextId { index: 9120 });
    v.insert("#anon_color-functions_2".to_string(), ContextId { index: 8984 });
    v.insert("#anon_sass-interpolation_0".to_string(), ContextId { index: 9058 });
    v.insert("#anon_color-adjuster-functions_7".to_string(), ContextId { index: 8979 });
    v.insert("#anon_at-rules_5".to_string(), ContextId { index: 8916 });
    v.insert("#anon_builtin-functions_38".to_string(), ContextId { index: 8957 });
    v.insert("#anon_selectors_2".to_string(), ContextId { index: 9071 });
    v.insert("#anon_attr-function_2".to_string(), ContextId { index: 8924 });
    v.insert("#anon_custom-element-selectors_4".to_string(), ContextId { index: 9000 });
    v.insert("#anon_filter-functions_1".to_string(), ContextId { index: 9004 });
    v.insert("#anon_at-rules_11".to_string(), ContextId { index: 8896 });
    v.insert("#anon_custom-element-selectors_3".to_string(), ContextId { index: 8999 });
    v.insert("#anon_builtin-functions_32".to_string(), ContextId { index: 8951 });
    v.insert("#anon_at-rules_0".to_string(), ContextId { index: 8893 });
    v.insert("comma-delimiter".to_string(), ContextId { index: 9099 });
    v.insert("sass-custom-functions".to_string(), ContextId { index: 9139 });
    v.insert("numeric-values".to_string(), ContextId { index: 9128 });
    v.insert("property-values".to_string(), ContextId { index: 9133 });
    v.insert("#anon_builtin-functions_23".to_string(), ContextId { index: 8941 });
    v.insert("#anon_properties_3".to_string(), ContextId { index: 9038 });
    v.insert("#anon_builtin-functions_24".to_string(), ContextId { index: 8942 });
    v.insert("#anon_builtin-functions_25".to_string(), ContextId { index: 8943 });
    v.insert("#anon_color-adjuster-functions_5".to_string(), ContextId { index: 8977 });
    v.insert("#anon_cross-fade-function_0".to_string(), ContextId { index: 8994 });
    v.insert("#anon_comment-line_0".to_string(), ContextId { index: 8993 });
    v.insert("#anon_regexp-function_1".to_string(), ContextId { index: 9055 });
    v.insert("#anon_color-adjuster-functions_1".to_string(), ContextId { index: 8973 });
    v.insert("#anon_at-rules_20".to_string(), ContextId { index: 8906 });
    v.insert("#anon_selectors_0".to_string(), ContextId { index: 9065 });
    v.insert("frontmatter".to_string(), ContextId { index: 9109 });
    v.insert("#anon_color-functions_0".to_string(), ContextId { index: 8982 });
    v.insert("#anon_image-function_0".to_string(), ContextId { index: 9019 });
    v.insert("#anon_color-functions_8".to_string(), ContextId { index: 8990 });
    v.insert("#anon_builtin-functions_3".to_string(), ContextId { index: 8948 });
    v.insert("#anon_pseudo-classes_2".to_string(), ContextId { index: 9047 });
    v.insert("image-type".to_string(), ContextId { index: 9115 });
    v.insert("#anon_pseudo-classes_4".to_string(), ContextId { index: 9049 });
    v.insert("pseudo-elements".to_string(), ContextId { index: 9135 });
    v.insert("#anon_at-rules_26".to_string(), ContextId { index: 8912 });
    v.insert("#anon_builtin-functions_41".to_string(), ContextId { index: 8961 });
    v.insert("#anon_builtin-functions_34".to_string(), ContextId { index: 8953 });
    v.insert("#anon_at-rules_23".to_string(), ContextId { index: 8909 });
    v.insert("color-values".to_string(), ContextId { index: 9098 });
    v.insert("#anon_at-rules_22".to_string(), ContextId { index: 8908 });
    v.insert("#anon_pseudo-classes_6".to_string(), ContextId { index: 9051 });
    v.insert("color-adjuster-operators".to_string(), ContextId { index: 9095 });
    v.insert("#anon_interpolated-selectors_2".to_string(), ContextId { index: 9026 });
    v.insert("string-content".to_string(), ContextId { index: 9152 });
    v.insert("#anon_sass-mixin-def_0".to_string(), ContextId { index: 9061 });
    v.insert("#anon_builtin-functions_12".to_string(), ContextId { index: 8929 });
    v.insert("#anon_custom-element-selectors_0".to_string(), ContextId { index: 8996 });
    v.insert("#anon_regexp-function_0".to_string(), ContextId { index: 9054 });
    v.insert("#anon_custom-element-selectors_1".to_string(), ContextId { index: 8997 });
    v.insert("#anon_sass-mixin-def_1".to_string(), ContextId { index: 9062 });
    v.insert("#anon_builtin-functions_20".to_string(), ContextId { index: 8938 });
    v.insert("#anon_builtin-functions_7".to_string(), ContextId { index: 8968 });
    v.insert("#anon_sass-custom-functions_0".to_string(), ContextId { index: 9056 });
    v.insert("#anon_pseudo-classes_7".to_string(), ContextId { index: 9052 });
    v.insert("#anon_color-adjuster-functions_2".to_string(), ContextId { index: 8974 });
    v.insert("#anon_selectors_5".to_string(), ContextId { index: 9074 });
    v.insert("#anon_gradient-functions_3".to_string(), ContextId { index: 9018 });
    v.insert("#anon_domain-function_0".to_string(), ContextId { index: 9001 });
    v.insert("#anon_pseudo-classes_0".to_string(), ContextId { index: 9045 });
    v.insert("#anon_at-rules_8".to_string(), ContextId { index: 8919 });
    v.insert("#anon_properties_1".to_string(), ContextId { index: 9036 });
    v.insert("#anon_filter-functions_2".to_string(), ContextId { index: 9005 });
    v.insert("interpolated-selector-body".to_string(), ContextId { index: 9118 });
    v.insert("#anon_at-rules_13".to_string(), ContextId { index: 8898 });
    v.insert("#anon_color-functions_4".to_string(), ContextId { index: 8986 });
    v.insert("#anon_minmax-function_1".to_string(), ContextId { index: 9034 });
    v.insert("#anon_selectors_13".to_string(), ContextId { index: 9070 });
    v.insert("resolution-type".to_string(), ContextId { index: 9138 });
    v.insert("#anon_properties_7".to_string(), ContextId { index: 9042 });
    v
  }
} }