
#![allow(unused_imports)]
#![allow(dead_code)]

use jirs_syntect::{*, parsing::*};
use lazycell::AtomicLazyCell;

#[inline(always)]
pub fn load() -> SyntaxReference {
        SyntaxReference {  name: "Java".to_string(),
  file_extensions: vec!["java".to_string(),"bsh".to_string()],
  scope: Scope { a: 844596728823808, b: 0 },
  first_line_match: None,
  hidden: false,
  variables: {
    let mut v = std::collections::HashMap::new();
    v.insert("lambda_lookahead".to_string(), "(?:\\(.*\\)|{{id}})\\s*->".to_string());
    v.insert("pexponent".to_string(), "(?:[pP]{{exponent}})".to_string());
    v.insert("storage_modifiers".to_string(), "(?:public|private|protected|static|final|native|synchronized|strictfp|abstract|transient|default|volatile)".to_string());
    v.insert("exponent".to_string(), "[-+]?{{ddigits}}".to_string());
    v.insert("uppercase_id".to_string(), "(?:[_$]*\\p{Lu}[\\p{Lu}\\p{N}_$]*\\b)".to_string());
    v.insert("lowercase_id".to_string(), "(?:[_$]*\\p{Ll}[\\p{Ll}\\p{N}_$]*\\b)".to_string());
    v.insert("before_fqn".to_string(), "(?={{lowercase_id}}\\s*\\.)".to_string());
    v.insert("classcase_id".to_string(), "(?:\\p{Lu}[\\p{L}\\p{N}_$]*)".to_string());
    v.insert("primitives".to_string(), "(?:boolean|byte|char|short|int|float|long|double)".to_string());
    v.insert("eexponent".to_string(), "(?:[eE]{{exponent}})".to_string());
    v.insert("ddigits0".to_string(), "\\d[\\d_]*?(_*)".to_string());
    v.insert("ddigits".to_string(), "(?:(_*){{ddigits0}})".to_string());
    v.insert("hdigits".to_string(), "(?:(_*)\\h[\\h_]*?(_*))".to_string());
    v.insert("id".to_string(), "(?:[\\p{L}_$][\\p{L}\\p{N}_$]*)".to_string());
    v
  },
  contexts: {
    let mut v = std::collections::HashMap::new();
    v.insert("support-type-module".to_string(), ContextId { index: 2391 });
    v.insert("#anon_array-definition_1".to_string(), ContextId { index: 2229 });
    v.insert("after-inherited-object-type-reference".to_string(), ContextId { index: 2285 });
    v.insert("annotations".to_string(), ContextId { index: 2296 });
    v.insert("#anon_enum-body_2".to_string(), ContextId { index: 2241 });
    v.insert("#anon_keywords-control_2".to_string(), ContextId { index: 2251 });
    v.insert("#anon_support-type-module_0".to_string(), ContextId { index: 2279 });
    v.insert("array-definition".to_string(), ContextId { index: 2300 });
    v.insert("#anon_after-object-type_0".to_string(), ContextId { index: 2219 });
    v.insert("assignment".to_string(), ContextId { index: 2303 });
    v.insert("class-meta".to_string(), ContextId { index: 2310 });
    v.insert("#anon_comments-inline_1".to_string(), ContextId { index: 2236 });
    v.insert("#anon_static-import-statement-body_1".to_string(), ContextId { index: 2276 });
    v.insert("declaration-statement-parens".to_string(), ContextId { index: 2319 });
    v.insert("#anon_annotation-array-initialization_0".to_string(), ContextId { index: 2220 });
    v.insert("#anon_exports-or-opens-statement_1".to_string(), ContextId { index: 2243 });
    v.insert("generic-type-argument".to_string(), ContextId { index: 2327 });
    v.insert("comments-inline".to_string(), ContextId { index: 2317 });
    v.insert("generic-type-terminator".to_string(), ContextId { index: 2333 });
    v.insert("lambdas".to_string(), ContextId { index: 2352 });
    v.insert("module".to_string(), ContextId { index: 2356 });
    v.insert("object-and-array-types-no-fqn".to_string(), ContextId { index: 2363 });
    v.insert("uses-statement-scope".to_string(), ContextId { index: 2394 });
    v.insert("#anon_comments-inline_0".to_string(), ContextId { index: 2235 });
    v.insert("after-annotation-type-reference".to_string(), ContextId { index: 2283 });
    v.insert("after-generic-in-instantiation".to_string(), ContextId { index: 2284 });
    v.insert("#anon_enum-body_1".to_string(), ContextId { index: 2240 });
    v.insert("package".to_string(), ContextId { index: 2371 });
    v.insert("throws".to_string(), ContextId { index: 2392 });
    v.insert("var-type".to_string(), ContextId { index: 2395 });
    v.insert("class".to_string(), ContextId { index: 2306 });
    v.insert("after-object-and-array-types".to_string(), ContextId { index: 2286 });
    v.insert("#anon_import-statement-body_0".to_string(), ContextId { index: 2245 });
    v.insert("#anon_keywords-control_3".to_string(), ContextId { index: 2252 });
    v.insert("enum-block".to_string(), ContextId { index: 2321 });
    v.insert("#anon_module-identifier_0".to_string(), ContextId { index: 2260 });
    v.insert("#anon_strings_0".to_string(), ContextId { index: 2277 });
    v.insert("generic-type-invocation".to_string(), ContextId { index: 2331 });
    v.insert("illegal-keywords".to_string(), ContextId { index: 2334 });
    v.insert("#anon_anonymous-classes-and-new_0".to_string(), ContextId { index: 2227 });
    v.insert("#anon_object-construction_1".to_string(), ContextId { index: 2265 });
    v.insert("instantiation".to_string(), ContextId { index: 2347 });
    v.insert("#anon_annotation-parameters_1".to_string(), ContextId { index: 2223 });
    v.insert("class-body".to_string(), ContextId { index: 2308 });
    v.insert("#anon_enum-body_0".to_string(), ContextId { index: 2239 });
    v.insert("generic-type-extends-multiple-bounds".to_string(), ContextId { index: 2330 });
    v.insert("#anon_module_1".to_string(), ContextId { index: 2262 });
    v.insert("generic-type-bounds".to_string(), ContextId { index: 2328 });
    v.insert("#anon_import-statement_0".to_string(), ContextId { index: 2247 });
    v.insert("annotation-default".to_string(), ContextId { index: 2292 });
    v.insert("#anon_object-and-array-types_0".to_string(), ContextId { index: 2263 });
    v.insert("module-statement-terminator".to_string(), ContextId { index: 2361 });
    v.insert("exports-or-opens-statement".to_string(), ContextId { index: 2323 });
    v.insert("module-body-content".to_string(), ContextId { index: 2358 });
    v.insert("provides-with-statement".to_string(), ContextId { index: 2378 });
    v.insert("strings-common".to_string(), ContextId { index: 2390 });
    v.insert("class-block".to_string(), ContextId { index: 2307 });
    v.insert("immediate_POP".to_string(), ContextId { index: 2338 });
    v.insert("generic-type-declaration".to_string(), ContextId { index: 2329 });
    v.insert("#anon_keywords-control_1".to_string(), ContextId { index: 2250 });
    v.insert("annotation-array-initialization".to_string(), ContextId { index: 2291 });
    v.insert("illegal-semicolon".to_string(), ContextId { index: 2337 });
    v.insert("import-wildcard".to_string(), ContextId { index: 2344 });
    v.insert("import-statement".to_string(), ContextId { index: 2342 });
    v.insert("any_POP".to_string(), ContextId { index: 2298 });
    v.insert("object-types".to_string(), ContextId { index: 2369 });
    v.insert("#anon_throws_0".to_string(), ContextId { index: 2280 });
    v.insert("__main".to_string(), ContextId { index: 2281 });
    v.insert("method-invocations".to_string(), ContextId { index: 2355 });
    v.insert("#anon_class-block_0".to_string(), ContextId { index: 2231 });
    v.insert("punctuation-separator-comma".to_string(), ContextId { index: 2380 });
    v.insert("#anon_class-extends_1".to_string(), ContextId { index: 2233 });
    v.insert("__start".to_string(), ContextId { index: 2282 });
    v.insert("fields-and-methods".to_string(), ContextId { index: 2326 });
    v.insert("code-block".to_string(), ContextId { index: 2314 });
    v.insert("dot-separated-identifier".to_string(), ContextId { index: 2320 });
    v.insert("anonymous-classes-and-new".to_string(), ContextId { index: 2297 });
    v.insert("module-body".to_string(), ContextId { index: 2357 });
    v.insert("requires-statement".to_string(), ContextId { index: 2382 });
    v.insert("object-construction".to_string(), ContextId { index: 2364 });
    v.insert("stray-parens".to_string(), ContextId { index: 2388 });
    v.insert("#anon_module-body_0".to_string(), ContextId { index: 2259 });
    v.insert("after-object-type".to_string(), ContextId { index: 2287 });
    v.insert("#anon_annotation-default_0".to_string(), ContextId { index: 2221 });
    v.insert("#anon_annotations_1".to_string(), ContextId { index: 2226 });
    v.insert("#anon_keywords-control_0".to_string(), ContextId { index: 2249 });
    v.insert("array-brackets".to_string(), ContextId { index: 2299 });
    v.insert("#anon_assignment_0".to_string(), ContextId { index: 2230 });
    v.insert("field-or-method".to_string(), ContextId { index: 2325 });
    v.insert("generic-type-parameter".to_string(), ContextId { index: 2332 });
    v.insert("#anon_package-statement_1".to_string(), ContextId { index: 2269 });
    v.insert("static-code-block".to_string(), ContextId { index: 2384 });
    v.insert("class-type".to_string(), ContextId { index: 2312 });
    v.insert("punctuation-accessor-dot".to_string(), ContextId { index: 2379 });
    v.insert("lambda-arrow".to_string(), ContextId { index: 2350 });
    v.insert("static-import-statement-body".to_string(), ContextId { index: 2385 });
    v.insert("static-assignment".to_string(), ContextId { index: 2383 });
    v.insert("illegal-open-block".to_string(), ContextId { index: 2335 });
    v.insert("object-type-instantiation-no-fqn".to_string(), ContextId { index: 2366 });
    v.insert("#anon_enum-block_0".to_string(), ContextId { index: 2238 });
    v.insert("code".to_string(), ContextId { index: 2313 });
    v.insert("#anon_static-assignment_0".to_string(), ContextId { index: 2273 });
    v.insert("import-constant".to_string(), ContextId { index: 2340 });
    v.insert("keywords".to_string(), ContextId { index: 2348 });
    v.insert("module-identifier".to_string(), ContextId { index: 2359 });
    v.insert("strings".to_string(), ContextId { index: 2389 });
    v.insert("#anon_field-or-method_0".to_string(), ContextId { index: 2244 });
    v.insert("#anon_declaration-statement-parens_0".to_string(), ContextId { index: 2237 });
    v.insert("#anon_keywords_0".to_string(), ContextId { index: 2253 });
    v.insert("#anon_package-statement_0".to_string(), ContextId { index: 2268 });
    v.insert("#anon_parens_0".to_string(), ContextId { index: 2271 });
    v.insert("#anon_object-construction_2".to_string(), ContextId { index: 2266 });
    v.insert("inherited-object-type-reference".to_string(), ContextId { index: 2345 });
    v.insert("enum-body".to_string(), ContextId { index: 2322 });
    v.insert("array-initialization".to_string(), ContextId { index: 2301 });
    v.insert("#anon_strings_1".to_string(), ContextId { index: 2278 });
    v.insert("after-object-type-in-instantiation".to_string(), ContextId { index: 2288 });
    v.insert("object-type-fqn".to_string(), ContextId { index: 2365 });
    v.insert("#anon_exports-or-opens-statement_0".to_string(), ContextId { index: 2242 });
    v.insert("storage-modifiers".to_string(), ContextId { index: 2386 });
    v.insert("comments".to_string(), ContextId { index: 2316 });
    v.insert("provides-statement-scope".to_string(), ContextId { index: 2377 });
    v.insert("stray-braces".to_string(), ContextId { index: 2387 });
    v.insert("#anon_lambda-params_0".to_string(), ContextId { index: 2255 });
    v.insert("constants-and-special-vars".to_string(), ContextId { index: 2318 });
    v.insert("inherited-object-type-reference-no-fqn".to_string(), ContextId { index: 2346 });
    v.insert("lambda-params".to_string(), ContextId { index: 2351 });
    v.insert("method".to_string(), ContextId { index: 2354 });
    v.insert("#anon_inherited-object-type-reference_0".to_string(), ContextId { index: 2248 });
    v.insert("parameters".to_string(), ContextId { index: 2373 });
    v.insert("annotation-parameters".to_string(), ContextId { index: 2293 });
    v.insert("class-name".to_string(), ContextId { index: 2311 });
    v.insert("primitive-types".to_string(), ContextId { index: 2375 });
    v.insert("#anon_lambda-arrow_0".to_string(), ContextId { index: 2254 });
    v.insert("import-class".to_string(), ContextId { index: 2339 });
    v.insert("annotation-type-reference".to_string(), ContextId { index: 2295 });
    v.insert("#anon_method_1".to_string(), ContextId { index: 2258 });
    v.insert("#anon_annotation-parameters_0".to_string(), ContextId { index: 2222 });
    v.insert("before-next-field".to_string(), ContextId { index: 2304 });
    v.insert("object-type-reference".to_string(), ContextId { index: 2367 });
    v.insert("parens".to_string(), ContextId { index: 2374 });
    v.insert("class-extends".to_string(), ContextId { index: 2309 });
    v.insert("code-block-include".to_string(), ContextId { index: 2315 });
    v.insert("#anon_annotation-type-reference_0".to_string(), ContextId { index: 2224 });
    v.insert("all-types".to_string(), ContextId { index: 2290 });
    v.insert("#anon_package-statement_2".to_string(), ContextId { index: 2270 });
    v.insert("illegal-parens-terminators".to_string(), ContextId { index: 2336 });
    v.insert("import-function".to_string(), ContextId { index: 2341 });
    v.insert("array-initialization-common".to_string(), ContextId { index: 2302 });
    v.insert("package-statement".to_string(), ContextId { index: 2372 });
    v.insert("annotation-type-no-fqn".to_string(), ContextId { index: 2294 });
    v.insert("#anon_method_0".to_string(), ContextId { index: 2257 });
    v.insert("#anon_code-block-include_0".to_string(), ContextId { index: 2234 });
    v.insert("#anon_object-construction_0".to_string(), ContextId { index: 2264 });
    v.insert("#anon_static-import-statement-body_0".to_string(), ContextId { index: 2275 });
    v.insert("object-and-array-types".to_string(), ContextId { index: 2362 });
    v.insert("exports-statement-scope".to_string(), ContextId { index: 2324 });
    v.insert("punctuation-terminator-semicolon".to_string(), ContextId { index: 2381 });
    v.insert("#anon_method-invocations_0".to_string(), ContextId { index: 2256 });
    v.insert("before-next-import".to_string(), ContextId { index: 2305 });
    v.insert("module-identifier-scope".to_string(), ContextId { index: 2360 });
    v.insert("#anon_class-extends_0".to_string(), ContextId { index: 2232 });
    v.insert("#anon_object-type-reference_0".to_string(), ContextId { index: 2267 });
    v.insert("import-statement-body".to_string(), ContextId { index: 2343 });
    v.insert("#anon_import-statement-body_1".to_string(), ContextId { index: 2246 });
    v.insert("#anon_annotations_0".to_string(), ContextId { index: 2225 });
    v.insert("#anon_provides-with-statement_0".to_string(), ContextId { index: 2272 });
    v.insert("object-type-reference-no-fqn".to_string(), ContextId { index: 2368 });
    v.insert("main".to_string(), ContextId { index: 2353 });
    v.insert("prototype".to_string(), ContextId { index: 2376 });
    v.insert("#anon_static-code-block_0".to_string(), ContextId { index: 2274 });
    v.insert("keywords-control".to_string(), ContextId { index: 2349 });
    v.insert("opens-statement-scope".to_string(), ContextId { index: 2370 });
    v.insert("uppercase-identifiers".to_string(), ContextId { index: 2393 });
    v.insert("#anon_array-definition_0".to_string(), ContextId { index: 2228 });
    v.insert("#anon_module_0".to_string(), ContextId { index: 2261 });
    v.insert("after-object-type-reference".to_string(), ContextId { index: 2289 });
    v
  }
} }