
#![allow(unused_imports)]
#![allow(dead_code)]

use jirs_syntect::{*, parsing::*};
use lazycell::AtomicLazyCell;

#[inline(always)]
pub fn load() -> SyntaxReference {
        SyntaxReference {  name: "PHP Source".to_string(),
  file_extensions: vec![],
  scope: Scope { a: 844674038235136, b: 0 },
  first_line_match: None,
  hidden: true,
  variables: {
    let mut v = std::collections::HashMap::new();
    v.insert("identifier".to_string(), "\\b{{identifier_start}}[[:alnum:]_]*\\b".to_string());
    v.insert("path".to_string(), "\\\\?({{identifier}}\\\\)*{{identifier}}".to_string());
    v.insert("sql_indicator".to_string(), "\\s*(?:SELECT|INSERT|UPDATE|DELETE|CREATE|REPLACE|ALTER)\\b".to_string());
    v.insert("identifier_start".to_string(), "[[:alpha:]_]".to_string());
    v
  },
  contexts: {
    let mut v = std::collections::HashMap::new();
    v.insert("heredoc-javascript".to_string(), ContextId { index: 4123 });
    v.insert("#anon_embedded-html_1".to_string(), ContextId { index: 4002 });
    v.insert("#anon_php-doc_0".to_string(), ContextId { index: 4067 });
    v.insert("#anon_heredoc_20".to_string(), ContextId { index: 4040 });
    v.insert("#anon_function-use_0".to_string(), ContextId { index: 4018 });
    v.insert("#anon_heredoc_12".to_string(), ContextId { index: 4031 });
    v.insert("#anon_string-double-quoted_1".to_string(), ContextId { index: 4080 });
    v.insert("identifier-parts-as-path".to_string(), ContextId { index: 4129 });
    v.insert("statements".to_string(), ContextId { index: 4143 });
    v.insert("#anon_heredoc_6".to_string(), ContextId { index: 4050 });
    v.insert("#anon_heredoc_5".to_string(), ContextId { index: 4049 });
    v.insert("#anon_constants_0".to_string(), ContextId { index: 3999 });
    v.insert("heredoc-xml".to_string(), ContextId { index: 4126 });
    v.insert("#anon_heredoc_25".to_string(), ContextId { index: 4045 });
    v.insert("#anon_heredoc_26".to_string(), ContextId { index: 4046 });
    v.insert("#anon_function-call-parameters_0".to_string(), ContextId { index: 4012 });
    v.insert("#anon_heredoc-sql_0".to_string(), ContextId { index: 4025 });
    v.insert("function-body".to_string(), ContextId { index: 4113 });
    v.insert("#anon_expressions_5".to_string(), ContextId { index: 4008 });
    v.insert("#anon_string-backtick_0".to_string(), ContextId { index: 4078 });
    v.insert("class-builtin".to_string(), ContextId { index: 4103 });
    v.insert("#anon_class-name_0".to_string(), ContextId { index: 3993 });
    v.insert("#anon_function_0".to_string(), ContextId { index: 4019 });
    v.insert("use-statement".to_string(), ContextId { index: 4149 });
    v.insert("#anon_regex-double-quoted_0".to_string(), ContextId { index: 4068 });
    v.insert("function".to_string(), ContextId { index: 4112 });
    v.insert("identifier-parts".to_string(), ContextId { index: 4128 });
    v.insert("#anon_heredoc_16".to_string(), ContextId { index: 4035 });
    v.insert("heredoc-css".to_string(), ContextId { index: 4121 });
    v.insert("#anon_class-definition_1".to_string(), ContextId { index: 3990 });
    v.insert("#anon_heredoc_22".to_string(), ContextId { index: 4042 });
    v.insert("heredoc-sql".to_string(), ContextId { index: 4125 });
    v.insert("#anon_string-double-quoted_2".to_string(), ContextId { index: 4081 });
    v.insert("#anon_heredoc_1".to_string(), ContextId { index: 4028 });
    v.insert("#anon_string-single-quoted_2".to_string(), ContextId { index: 4085 });
    v.insert("invoke-call".to_string(), ContextId { index: 4132 });
    v.insert("item-access".to_string(), ContextId { index: 4134 });
    v.insert("strings".to_string(), ContextId { index: 4147 });
    v.insert("#anon_is-arrow-function_1".to_string(), ContextId { index: 4062 });
    v.insert("interpolation".to_string(), ContextId { index: 4131 });
    v.insert("support".to_string(), ContextId { index: 4148 });
    v.insert("use-statement-const".to_string(), ContextId { index: 4151 });
    v.insert("use-statement-function".to_string(), ContextId { index: 4152 });
    v.insert("#anon_interpolation_1".to_string(), ContextId { index: 4058 });
    v.insert("#anon_use-statement-function_0".to_string(), ContextId { index: 4088 });
    v.insert("#anon_class-body_3".to_string(), ContextId { index: 3987 });
    v.insert("string-backtick".to_string(), ContextId { index: 4144 });
    v.insert("use-statement-identifier-function-def".to_string(), ContextId { index: 4154 });
    v.insert("closure".to_string(), ContextId { index: 4106 });
    v.insert("#anon_constants_1".to_string(), ContextId { index: 4000 });
    v.insert("heredoc-html".to_string(), ContextId { index: 4122 });
    v.insert("#anon_interpolation_0".to_string(), ContextId { index: 4057 });
    v.insert("#anon_function-call-static_0".to_string(), ContextId { index: 4013 });
    v.insert("#anon_expressions_2".to_string(), ContextId { index: 4005 });
    v.insert("#anon_instantiation_0".to_string(), ContextId { index: 4055 });
    v.insert("#anon_heredoc_14".to_string(), ContextId { index: 4033 });
    v.insert("embedded-html".to_string(), ContextId { index: 4109 });
    v.insert("#anon_object_0".to_string(), ContextId { index: 4064 });
    v.insert("#anon_heredoc-javascript_0".to_string(), ContextId { index: 4023 });
    v.insert("#anon_function-call_0".to_string(), ContextId { index: 4014 });
    v.insert("#anon_heredoc-html_0".to_string(), ContextId { index: 4022 });
    v.insert("#anon_use-statement-identifier-class-def_0".to_string(), ContextId { index: 4089 });
    v.insert("after-function-call".to_string(), ContextId { index: 4097 });
    v.insert("after-identifier".to_string(), ContextId { index: 4098 });
    v.insert("#anon_comments_1".to_string(), ContextId { index: 3996 });
    v.insert("#anon_string-double-quoted_0".to_string(), ContextId { index: 4079 });
    v.insert("#anon_string-single-quoted_1".to_string(), ContextId { index: 4084 });
    v.insert("#anon_interpolation_3".to_string(), ContextId { index: 4060 });
    v.insert("#anon_statements_0".to_string(), ContextId { index: 4074 });
    v.insert("#anon_heredoc_2".to_string(), ContextId { index: 4039 });
    v.insert("#anon_regex-double-quoted_1".to_string(), ContextId { index: 4069 });
    v.insert("#anon_parameter-default-types_1".to_string(), ContextId { index: 4066 });
    v.insert("#anon_identifier-constant-pop_0".to_string(), ContextId { index: 4054 });
    v.insert("class-body".to_string(), ContextId { index: 4102 });
    v.insert("#anon_heredoc_17".to_string(), ContextId { index: 4036 });
    v.insert("#anon_expressions_8".to_string(), ContextId { index: 4011 });
    v.insert("#anon_function-parameters_0".to_string(), ContextId { index: 4016 });
    v.insert("#anon_heredoc_19".to_string(), ContextId { index: 4038 });
    v.insert("#anon_heredoc_10".to_string(), ContextId { index: 4029 });
    v.insert("#anon_class-body_0".to_string(), ContextId { index: 3984 });
    v.insert("#anon_class-definition_0".to_string(), ContextId { index: 3989 });
    v.insert("#anon_heredoc-css_0".to_string(), ContextId { index: 4021 });
    v.insert("#anon_instantiation_1".to_string(), ContextId { index: 4056 });
    v.insert("#anon_use-statement-ns-class_0".to_string(), ContextId { index: 4093 });
    v.insert("#anon_expressions_4".to_string(), ContextId { index: 4007 });
    v.insert("main".to_string(), ContextId { index: 4135 });
    v.insert("php-doc".to_string(), ContextId { index: 4139 });
    v.insert("#anon_expressions_7".to_string(), ContextId { index: 4010 });
    v.insert("#anon_regex-single-quoted_0".to_string(), ContextId { index: 4070 });
    v.insert("#anon_heredoc_4".to_string(), ContextId { index: 4048 });
    v.insert("function-use".to_string(), ContextId { index: 4119 });
    v.insert("heredoc-json".to_string(), ContextId { index: 4124 });
    v.insert("#anon_function-call_1".to_string(), ContextId { index: 4015 });
    v.insert("regex-single-quoted".to_string(), ContextId { index: 4141 });
    v.insert("#anon_heredoc-xml_0".to_string(), ContextId { index: 4026 });
    v.insert("#anon_heredoc_8".to_string(), ContextId { index: 4052 });
    v.insert("#anon_statements_1".to_string(), ContextId { index: 4075 });
    v.insert("#anon_function_1".to_string(), ContextId { index: 4020 });
    v.insert("#anon_heredoc_24".to_string(), ContextId { index: 4044 });
    v.insert("__start".to_string(), ContextId { index: 4096 });
    v.insert("#anon_expressions_3".to_string(), ContextId { index: 4006 });
    v.insert("#anon_statements_2".to_string(), ContextId { index: 4076 });
    v.insert("#anon_use-statement_0".to_string(), ContextId { index: 4094 });
    v.insert("regex-double-quoted".to_string(), ContextId { index: 4140 });
    v.insert("single-line-php-tag".to_string(), ContextId { index: 4142 });
    v.insert("string-double-quoted".to_string(), ContextId { index: 4145 });
    v.insert("variables-no-item-access".to_string(), ContextId { index: 4157 });
    v.insert("#anon_expressions_0".to_string(), ContextId { index: 4003 });
    v.insert("function-call-static".to_string(), ContextId { index: 4116 });
    v.insert("use-statement-identifier-class-def".to_string(), ContextId { index: 4153 });
    v.insert("#anon_heredoc_23".to_string(), ContextId { index: 4043 });
    v.insert("#anon_heredoc_18".to_string(), ContextId { index: 4037 });
    v.insert("#anon_use-statement-identifier-class-def_1".to_string(), ContextId { index: 4090 });
    v.insert("#anon_class-definition_3".to_string(), ContextId { index: 3992 });
    v.insert("function-call".to_string(), ContextId { index: 4114 });
    v.insert("string-single-quoted".to_string(), ContextId { index: 4146 });
    v.insert("expressions".to_string(), ContextId { index: 4110 });
    v.insert("#anon_class-body_4".to_string(), ContextId { index: 3988 });
    v.insert("#anon_embedded-html_0".to_string(), ContextId { index: 4001 });
    v.insert("#anon_function-parameters_1".to_string(), ContextId { index: 4017 });
    v.insert("fn-function-call".to_string(), ContextId { index: 4111 });
    v.insert("#anon_expressions_1".to_string(), ContextId { index: 4004 });
    v.insert("#anon_expressions_6".to_string(), ContextId { index: 4009 });
    v.insert("#anon_comments_0".to_string(), ContextId { index: 3995 });
    v.insert("#anon_single-line-php-tag_0".to_string(), ContextId { index: 4073 });
    v.insert("#anon_string-single-quoted_0".to_string(), ContextId { index: 4083 });
    v.insert("identifier-constant-pop".to_string(), ContextId { index: 4127 });
    v.insert("#anon_use-statement-const_0".to_string(), ContextId { index: 4087 });
    v.insert("is-arrow-function".to_string(), ContextId { index: 4133 });
    v.insert("parameter-default-types".to_string(), ContextId { index: 4138 });
    v.insert("#anon_comments_2".to_string(), ContextId { index: 3997 });
    v.insert("#anon_heredoc_9".to_string(), ContextId { index: 4053 });
    v.insert("#anon_heredoc_0".to_string(), ContextId { index: 4027 });
    v.insert("__main".to_string(), ContextId { index: 4095 });
    v.insert("class-definition".to_string(), ContextId { index: 4104 });
    v.insert("#anon_heredoc_11".to_string(), ContextId { index: 4030 });
    v.insert("#anon_heredoc_15".to_string(), ContextId { index: 4034 });
    v.insert("#anon_class-definition_2".to_string(), ContextId { index: 3991 });
    v.insert("#anon_heredoc_21".to_string(), ContextId { index: 4041 });
    v.insert("#anon_parameter-default-types_0".to_string(), ContextId { index: 4065 });
    v.insert("#anon_item-access_0".to_string(), ContextId { index: 4063 });
    v.insert("#anon_regex-single-quoted_1".to_string(), ContextId { index: 4071 });
    v.insert("function-return-type".to_string(), ContextId { index: 4118 });
    v.insert("instantiation".to_string(), ContextId { index: 4130 });
    v.insert("#anon_heredoc_3".to_string(), ContextId { index: 4047 });
    v.insert("#anon_class-body_2".to_string(), ContextId { index: 3986 });
    v.insert("class".to_string(), ContextId { index: 4101 });
    v.insert("use-statement-common".to_string(), ContextId { index: 4150 });
    v.insert("#anon_class-body_1".to_string(), ContextId { index: 3985 });
    v.insert("#anon_regex-single-quoted_2".to_string(), ContextId { index: 4072 });
    v.insert("use-statement-ns-class".to_string(), ContextId { index: 4155 });
    v.insert("#anon_interpolation_2".to_string(), ContextId { index: 4059 });
    v.insert("#anon_heredoc_7".to_string(), ContextId { index: 4051 });
    v.insert("#anon_closure_0".to_string(), ContextId { index: 3994 });
    v.insert("#anon_string-double-quoted_3".to_string(), ContextId { index: 4082 });
    v.insert("#anon_string-single-quoted_3".to_string(), ContextId { index: 4086 });
    v.insert("variables".to_string(), ContextId { index: 4156 });
    v.insert("#anon_comments_3".to_string(), ContextId { index: 3998 });
    v.insert("#anon_use-statement-identifier-function-def_1".to_string(), ContextId { index: 4092 });
    v.insert("arrow-function".to_string(), ContextId { index: 4099 });
    v.insert("constants".to_string(), ContextId { index: 4108 });
    v.insert("heredoc".to_string(), ContextId { index: 4120 });
    v.insert("#anon_is-arrow-function_0".to_string(), ContextId { index: 4061 });
    v.insert("function-parameters".to_string(), ContextId { index: 4117 });
    v.insert("#anon_heredoc_13".to_string(), ContextId { index: 4032 });
    v.insert("object".to_string(), ContextId { index: 4137 });
    v.insert("#anon_heredoc-json_0".to_string(), ContextId { index: 4024 });
    v.insert("#anon_statements_3".to_string(), ContextId { index: 4077 });
    v.insert("block".to_string(), ContextId { index: 4100 });
    v.insert("function-call-parameters".to_string(), ContextId { index: 4115 });
    v.insert("numbers".to_string(), ContextId { index: 4136 });
    v.insert("comments".to_string(), ContextId { index: 4107 });
    v.insert("#anon_use-statement-identifier-function-def_0".to_string(), ContextId { index: 4091 });
    v.insert("class-name".to_string(), ContextId { index: 4105 });
    v
  }
} }