
#![allow(unused_imports)]
#![allow(dead_code)]

use jirs_syntect::{*, parsing::*};
use lazycell::AtomicLazyCell;

#[inline(always)]
pub fn load() -> SyntaxReference {
        SyntaxReference {  name: "Perl".to_string(),
  file_extensions: vec!["pl".to_string(),"pc".to_string(),"pm".to_string(),"pmc".to_string(),"pod".to_string(),"t".to_string()],
  scope: Scope { a: 844686923137024, b: 0 },
  first_line_match: Some("(?xi:\n  ^\\#! .* \\bperl\\b |                     # shebang\n  ^\\# \\s* -\\*- [^*]* perl [^*]* -\\*-     # editorconfig\n)".to_string()),
  hidden: false,
  variables: {
    let mut v = std::collections::HashMap::new();
    v.insert("pod".to_string(), "={{identifier}}".to_string());
    v.insert("regexp_flags".to_string(), "[msixpodualngcer]+\\b".to_string());
    v.insert("builtin_functions".to_string(), "\\b(?x:\n  abs|accept|alarm|atan2|bind|binmode|bless|chdir|chmod|\n  chomp|chop|chown|chr|chroot|close|closedir|connect|cos|crypt|\n  dbmclose|dbmopen|defined|delete|each|endgrent|endhostent|\n  endnetent|endprotoent|endpwent|endservent|eof|eval|evalbytes|exec|\n  exists|exp|fc|fcntl|fileno|flock|fork|formline|getc|\n  getgrent|getgrgid|getgrnam|gethostbyaddr|gethostbyname|gethostent|\n  getlogin|getnetbyaddr|getnetbyname|getnetent|getpeername|getpgrp|\n  getppid|getpriority|getprotobyname|getprotobynumber|getprotoent|\n  getpwent|getpwnam|getpwuid|getservbyname|getservbyport|getservent|\n  getsockname|getsockopt|glob|gmtime|grep|hex|index|int|ioctl|join|\n  keys|kill|lc|lcfirst|length|link|listen|localtime|lock|log|\n  lstat|map|mkdir|msgctl|msgget|msgrcv|msgsnd|oct|open|opendir|ord|\n  pack|pipe|pop|pos|print|printf|prototype|push|quotemeta|\n  rand|read|readdir|readline|readlink|readpipe|recv|ref|rename|\n  reset|reverse|rewinddir|rindex|rmdir|say|scalar|seek|seekdir|select|\n  semctl|semget|semop|send|setgrent|sethostent|setnetent|setpgrp|\n  setpriority|setprotoent|setpwent|setservent|setsockopt|shift|shmctl|\n  shmget|shmread|shmwrite|shutdown|sin|sleep|socket|socketpair|sort|\n  splice|split|sprintf|sqrt|srand|stat|study|substr|symlink|syscall|\n  sysopen|sysread|sysseek|system|syswrite|tell|telldir|tie|tied|time|\n  times|truncate|uc|ucfirst|umask|undef|unlink|unpack|unshift|untie|\n  utime|values|vec|wait|waitpid|wantarray|warn|write\n){{break}}".to_string());
    v.insert("identifier".to_string(), "\\b[_[:alpha:]]\\w*\\b".to_string());
    v.insert("no_escape_behind".to_string(), "(?<![^\\\\]\\\\)(?<![^\\\\][\\\\]{3})".to_string());
    v.insert("operator_keywords".to_string(), "and|or|xor|as|cmp|eq|gt|ge|lt|le|ne|not|x".to_string());
    v.insert("builtin_variables".to_string(), "(?x:\n  [_0abF]|ACCUMULATOR|ARG[CV]?|BASETIME|CHILD_ERROR|COMPILING|DEBUGGING|\n  EFFECTIVE_GROUP_ID|EFFECTIVE_USER_ID|EGID|ENV|ERRNO|EUID|EVAL_ERROR|\n  EXCEPTIONS_BEING_CAUGHT|EXECUTABLE_NAME|EXTENDED_OS_ERROR|FORMAT_FORMFEED|\n  FORMAT_LINE_BREAK_CHARACTERS|FORMAT_LINES_LEFT|FORMAT_LINES_PER_PAGE|\n  FORMAT_NAME|FORMAT_PAGE_NUMBER|FORMAT_TOP_NAME|GID|INPLACE_EDIT|\n  INPUT_LINE_NUMBER|INPUT_RECORD_SEPARATOR|INC|ISA|LAST_MATCH_END|\n  LAST_MATCH_START|LAST_PAREN_MATCH|LAST_REGEXP_CODE_RESULT|\n  LAST_SUBMATCH_RESULT|LIST_SEPARATOR|MATCH|NR|OFS|OLD_PERL_VERSION|ORS|\n  OS_ERROR|OSNAME|OUTPUT_AUTOFLUSH|OUTPUT_FIELD_SEPARATOR|\n  OUTPUT_RECORD_SEPARATOR|PERL_VERSION|PERLDB|PID|POSTMATCH|PREMATCH|\n  PROCESS_ID|PROGRAM_NAME|REAL_GROUP_ID|REAL_USER_ID|RS|SIG|\n  SUBSCRIPT_SEPARATOR|SUBSEP|SYSTEM_FD_MAX|UID|WARNING\n){{break}}".to_string());
    v.insert("regexp_delim".to_string(), "[^\\w\\s\\)\\]\\}\\>]".to_string());
    v.insert("reserved_words".to_string(), "\\b(?x:\n  # control keywords\n  default|else|elsif|given|if|unless|when|break|caller|continue|die|\n  do|dump|exit|goto|last|next|redo|return|wait|for|foreach|until|while|\n  # declaration keywords\n  package|require|use|no|sub|format|{{storage_keywords}}|\n  # word operators\n  {{operator_keywords}}|\n  # quoted like functions (are handled like keywords)\n  {{quoted_like_keywords}}\n)\\b".to_string());
    v.insert("break".to_string(), "\\b(?!::)".to_string());
    v.insert("quoted_like_keywords".to_string(), "m|q|qq|qr|qw|qx|s|tr|y".to_string());
    v.insert("qualified_reserved_words".to_string(), "(?:CORE::)?{{reserved_words}}".to_string());
    v.insert("storage_keywords".to_string(), "local|my|our|state".to_string());
    v
  },
  contexts: {
    let mut v = std::collections::HashMap::new();
    v.insert("#anon_comment-pod-formatting_1".to_string(), ContextId { index: 4198 });
    v.insert("#anon_comment-pod-embedded_5".to_string(), ContextId { index: 4192 });
    v.insert("interpolated-braces-nested".to_string(), ContextId { index: 4302 });
    v.insert("#anon_comment-pod-embedded_12".to_string(), ContextId { index: 4188 });
    v.insert("#anon_comment-pod-embedded_11".to_string(), ContextId { index: 4187 });
    v.insert("blocks-nested".to_string(), ContextId { index: 4270 });
    v.insert("sub-name".to_string(), ContextId { index: 4378 });
    v.insert("#anon_comment-pod-embedded_2".to_string(), ContextId { index: 4189 });
    v.insert("#anon_literal-brackets-nested_0".to_string(), ContextId { index: 4222 });
    v.insert("#anon_quoted-like-match_1".to_string(), ContextId { index: 4243 });
    v.insert("literal-brackets-nested".to_string(), ContextId { index: 4317 });
    v.insert("#anon_maybe-item-access_1".to_string(), ContextId { index: 4229 });
    v.insert("expressions-begin".to_string(), ContextId { index: 4291 });
    v.insert("interpolated-parens-pop".to_string(), ContextId { index: 4309 });
    v.insert("require-expression".to_string(), ContextId { index: 4349 });
    v.insert("eol-pop".to_string(), ContextId { index: 4289 });
    v.insert("string-heredoc".to_string(), ContextId { index: 4356 });
    v.insert("#anon_maybe-regexp-match_1".to_string(), ContextId { index: 4231 });
    v.insert("#anon_string-heredoc-javascript_1".to_string(), ContextId { index: 4251 });
    v.insert("main".to_string(), ContextId { index: 4323 });
    v.insert("#anon_comment-pod-embedded_9".to_string(), ContextId { index: 4196 });
    v.insert("parameters-end".to_string(), ContextId { index: 4332 });
    v.insert("#anon_interpolated-angle-pop_0".to_string(), ContextId { index: 4210 });
    v.insert("string-heredoc-css".to_string(), ContextId { index: 4358 });
    v.insert("string-heredoc-sql".to_string(), ContextId { index: 4366 });
    v.insert("imports".to_string(), ContextId { index: 4299 });
    v.insert("quoted-like-meta".to_string(), ContextId { index: 4345 });
    v.insert("require-body".to_string(), ContextId { index: 4347 });
    v.insert("#anon_string-heredoc-sql_1".to_string(), ContextId { index: 4255 });
    v.insert("quoted-like-args-literal".to_string(), ContextId { index: 4341 });
    v.insert("#anon_interpolated-parens-pop_0".to_string(), ContextId { index: 4217 });
    v.insert("maybe-regexp-match".to_string(), ContextId { index: 4325 });
    v.insert("#anon_comment-pod-formatting_3".to_string(), ContextId { index: 4200 });
    v.insert("#anon_comment-pod_0".to_string(), ContextId { index: 4206 });
    v.insert("#anon_string-heredoc-sql_0".to_string(), ContextId { index: 4254 });
    v.insert("#anon_variables-interpolation_0".to_string(), ContextId { index: 4266 });
    v.insert("#anon_quoted-like-args-substitution_2".to_string(), ContextId { index: 4241 });
    v.insert("else-pop".to_string(), ContextId { index: 4288 });
    v.insert("label".to_string(), ContextId { index: 4311 });
    v.insert("qualified-variables-path".to_string(), ContextId { index: 4336 });
    v.insert("quoted-like-args-substitution".to_string(), ContextId { index: 4343 });
    v.insert("string-heredoc-javascript".to_string(), ContextId { index: 4362 });
    v.insert("#anon_interpolated-generic-pop_0".to_string(), ContextId { index: 4215 });
    v.insert("quoted-like-args-pattern".to_string(), ContextId { index: 4342 });
    v.insert("#anon_comment-pod-formatting_0".to_string(), ContextId { index: 4197 });
    v.insert("#anon_comment-pod-embedded_7".to_string(), ContextId { index: 4194 });
    v.insert("#anon_literal-braces-pop_0".to_string(), ContextId { index: 4221 });
    v.insert("#anon_interpolated-angle-nested_0".to_string(), ContextId { index: 4209 });
    v.insert("#anon_comment-pod-embedded_0".to_string(), ContextId { index: 4184 });
    v.insert("#anon_string-heredoc-css_0".to_string(), ContextId { index: 4246 });
    v.insert("#anon_literal-parens-nested_0".to_string(), ContextId { index: 4225 });
    v.insert("#anon_string-quoted-double_0".to_string(), ContextId { index: 4260 });
    v.insert("#anon_comment-pod-embedded_6".to_string(), ContextId { index: 4193 });
    v.insert("brackets".to_string(), ContextId { index: 4272 });
    v.insert("comment-line".to_string(), ContextId { index: 4275 });
    v.insert("#anon_string-quoted-angle-pop_0".to_string(), ContextId { index: 4258 });
    v.insert("#anon_qualified-function-call_1".to_string(), ContextId { index: 4233 });
    v.insert("#anon_sub-parameters_0".to_string(), ContextId { index: 4264 });
    v.insert("comment-pod-body".to_string(), ContextId { index: 4277 });
    v.insert("constants-version".to_string(), ContextId { index: 4287 });
    v.insert("expressions-common".to_string(), ContextId { index: 4292 });
    v.insert("interpolated-parens-nested".to_string(), ContextId { index: 4308 });
    v.insert("groups".to_string(), ContextId { index: 4295 });
    v.insert("#anon_literal-brackets-pop_0".to_string(), ContextId { index: 4223 });
    v.insert("label-usage".to_string(), ContextId { index: 4312 });
    v.insert("qualifier".to_string(), ContextId { index: 4337 });
    v.insert("require-end".to_string(), ContextId { index: 4348 });
    v.insert("interpolated-braces-pop".to_string(), ContextId { index: 4303 });
    v.insert("string-format-body".to_string(), ContextId { index: 4353 });
    v.insert("__main".to_string(), ContextId { index: 4267 });
    v.insert("string-heredoc-expr".to_string(), ContextId { index: 4359 });
    v.insert("#anon_maybe-regexp-match_0".to_string(), ContextId { index: 4230 });
    v.insert("#anon_string-quoted-backtick_0".to_string(), ContextId { index: 4259 });
    v.insert("#anon_comment-pod-formatting_2".to_string(), ContextId { index: 4199 });
    v.insert("#anon_string-quoted-single_0".to_string(), ContextId { index: 4261 });
    v.insert("brackets-nested-body".to_string(), ContextId { index: 4274 });
    v.insert("#anon_main_0".to_string(), ContextId { index: 4227 });
    v.insert("comment-pod".to_string(), ContextId { index: 4276 });
    v.insert("package-version".to_string(), ContextId { index: 4330 });
    v.insert("interpolated-common".to_string(), ContextId { index: 4306 });
    v.insert("string-heredoc-html".to_string(), ContextId { index: 4360 });
    v.insert("#anon_qualified-function-call_0".to_string(), ContextId { index: 4232 });
    v.insert("string-quoted-double".to_string(), ContextId { index: 4370 });
    v.insert("sub-attributes-name".to_string(), ContextId { index: 4374 });
    v.insert("sub-parameters".to_string(), ContextId { index: 4379 });
    v.insert("variables-interpolation".to_string(), ContextId { index: 4387 });
    v.insert("string-quoted-backtick".to_string(), ContextId { index: 4369 });
    v.insert("string-heredoc-interpolated".to_string(), ContextId { index: 4361 });
    v.insert("qualified-function-call".to_string(), ContextId { index: 4333 });
    v.insert("interpolated-brackets-pop".to_string(), ContextId { index: 4305 });
    v.insert("string-format".to_string(), ContextId { index: 4352 });
    v.insert("sub-common".to_string(), ContextId { index: 4376 });
    v.insert("#anon_literal-generic-pop_0".to_string(), ContextId { index: 4224 });
    v.insert("variables-interpolation-body".to_string(), ContextId { index: 4388 });
    v.insert("string-heredoc-xml".to_string(), ContextId { index: 4367 });
    v.insert("unqualified-namespace".to_string(), ContextId { index: 4382 });
    v.insert("string-quoted-angle-pop".to_string(), ContextId { index: 4368 });
    v.insert("variable-body".to_string(), ContextId { index: 4384 });
    v.insert("package-end".to_string(), ContextId { index: 4328 });
    v.insert("#anon_string-heredoc-html_1".to_string(), ContextId { index: 4249 });
    v.insert("#anon_quoted-like-match_0".to_string(), ContextId { index: 4242 });
    v.insert("maybe-item-access".to_string(), ContextId { index: 4324 });
    v.insert("#anon_comment-pod-formatting_6".to_string(), ContextId { index: 4203 });
    v.insert("#anon_sub-path_0".to_string(), ContextId { index: 4265 });
    v.insert("#anon_comment-line_0".to_string(), ContextId { index: 4183 });
    v.insert("__start".to_string(), ContextId { index: 4268 });
    v.insert("blocks-nested-body".to_string(), ContextId { index: 4271 });
    v.insert("comment-pod-formatting".to_string(), ContextId { index: 4280 });
    v.insert("comment-pod-keyword".to_string(), ContextId { index: 4281 });
    v.insert("#anon_comment-pod-embedded_10".to_string(), ContextId { index: 4186 });
    v.insert("expressions".to_string(), ContextId { index: 4290 });
    v.insert("literal-angle-pop".to_string(), ContextId { index: 4314 });
    v.insert("variable-identifier".to_string(), ContextId { index: 4385 });
    v.insert("#anon_string-format-variable_0".to_string(), ContextId { index: 4245 });
    v.insert("quoted-like".to_string(), ContextId { index: 4338 });
    v.insert("#anon_interpolated-braces-pop_0".to_string(), ContextId { index: 4212 });
    v.insert("string-heredoc-plain".to_string(), ContextId { index: 4365 });
    v.insert("qualified-namespace".to_string(), ContextId { index: 4334 });
    v.insert("require-namespace".to_string(), ContextId { index: 4350 });
    v.insert("variable-not-operator".to_string(), ContextId { index: 4386 });
    v.insert("constants-numbers".to_string(), ContextId { index: 4285 });
    v.insert("#anon_interpolated-braces-nested_0".to_string(), ContextId { index: 4211 });
    v.insert("#anon_string-heredoc-html_0".to_string(), ContextId { index: 4248 });
    v.insert("interpolated-angle-pop".to_string(), ContextId { index: 4301 });
    v.insert("#anon_comment-pod-formatting_7".to_string(), ContextId { index: 4204 });
    v.insert("#anon_quoted-like-args-pattern_2".to_string(), ContextId { index: 4237 });
    v.insert("function-identifier".to_string(), ContextId { index: 4294 });
    v.insert("#anon_interpolated-parens-nested_0".to_string(), ContextId { index: 4216 });
    v.insert("brackets-nested".to_string(), ContextId { index: 4273 });
    v.insert("sub-attributes-parameters".to_string(), ContextId { index: 4375 });
    v.insert("#anon_comment-pod-embedded_4".to_string(), ContextId { index: 4191 });
    v.insert("#anon_imports_0".to_string(), ContextId { index: 4207 });
    v.insert("literal-angle-nested".to_string(), ContextId { index: 4313 });
    v.insert("string-format-variable".to_string(), ContextId { index: 4355 });
    v.insert("unqualified-function-call".to_string(), ContextId { index: 4381 });
    v.insert("comment-pod-format-body".to_string(), ContextId { index: 4279 });
    v.insert("literal-common".to_string(), ContextId { index: 4319 });
    v.insert("#anon_literal-parens-pop_0".to_string(), ContextId { index: 4226 });
    v.insert("comment-pod-embedded".to_string(), ContextId { index: 4278 });
    v.insert("constants-language".to_string(), ContextId { index: 4284 });
    v.insert("#anon_comment-pod-keyword_0".to_string(), ContextId { index: 4205 });
    v.insert("package-namespace".to_string(), ContextId { index: 4329 });
    v.insert("#anon_sub-attributes-name_0".to_string(), ContextId { index: 4262 });
    v.insert("qualified-variables".to_string(), ContextId { index: 4335 });
    v.insert("quoted-like-match".to_string(), ContextId { index: 4344 });
    v.insert("sub".to_string(), ContextId { index: 4372 });
    v.insert("quoted-like-substitution".to_string(), ContextId { index: 4346 });
    v.insert("#anon_qualified-namespace_0".to_string(), ContextId { index: 4234 });
    v.insert("constants-other".to_string(), ContextId { index: 4286 });
    v.insert("constants".to_string(), ContextId { index: 4282 });
    v.insert("expressions-nested".to_string(), ContextId { index: 4293 });
    v.insert("interpolated-generic-pop".to_string(), ContextId { index: 4307 });
    v.insert("sub-attributes".to_string(), ContextId { index: 4373 });
    v.insert("sub-path".to_string(), ContextId { index: 4380 });
    v.insert("#anon_interpolated-brackets-pop_0".to_string(), ContextId { index: 4214 });
    v.insert("interpolated-angle-nested".to_string(), ContextId { index: 4300 });
    v.insert("quoted-like-args-interpolated".to_string(), ContextId { index: 4340 });
    v.insert("string".to_string(), ContextId { index: 4351 });
    v.insert("#anon_string-heredoc-xml_1".to_string(), ContextId { index: 4257 });
    v.insert("#anon_interpolated-brackets-nested_0".to_string(), ContextId { index: 4213 });
    v.insert("sub-end".to_string(), ContextId { index: 4377 });
    v.insert("#anon_string-heredoc-json_0".to_string(), ContextId { index: 4252 });
    v.insert("constants-identifier".to_string(), ContextId { index: 4283 });
    v.insert("interpolated-brackets-nested".to_string(), ContextId { index: 4304 });
    v.insert("#anon_literal-angle-nested_0".to_string(), ContextId { index: 4218 });
    v.insert("string-heredoc-json".to_string(), ContextId { index: 4363 });
    v.insert("quoted-like-args-flags".to_string(), ContextId { index: 4339 });
    v.insert("string-heredoc-meta".to_string(), ContextId { index: 4364 });
    v.insert("#anon_literal-braces-nested_0".to_string(), ContextId { index: 4220 });
    v.insert("immediately-pop".to_string(), ContextId { index: 4298 });
    v.insert("package".to_string(), ContextId { index: 4327 });
    v.insert("string-quoted-single".to_string(), ContextId { index: 4371 });
    v.insert("#anon_quoted-like-args-substitution_1".to_string(), ContextId { index: 4240 });
    v.insert("#anon_maybe-item-access_0".to_string(), ContextId { index: 4228 });
    v.insert("blocks".to_string(), ContextId { index: 4269 });
    v.insert("groups-nested-body".to_string(), ContextId { index: 4297 });
    v.insert("literal-braces-pop".to_string(), ContextId { index: 4316 });
    v.insert("string-heredoc-body".to_string(), ContextId { index: 4357 });
    v.insert("#anon_string-format-body_0".to_string(), ContextId { index: 4244 });
    v.insert("#anon_literal-angle-pop_0".to_string(), ContextId { index: 4219 });
    v.insert("#anon_string-heredoc-json_1".to_string(), ContextId { index: 4253 });
    v.insert("keywords".to_string(), ContextId { index: 4310 });
    v.insert("literal-brackets-pop".to_string(), ContextId { index: 4318 });
    v.insert("groups-nested".to_string(), ContextId { index: 4296 });
    v.insert("literal-parens-pop".to_string(), ContextId { index: 4322 });
    v.insert("#anon_imports_1".to_string(), ContextId { index: 4208 });
    v.insert("parameters-begin".to_string(), ContextId { index: 4331 });
    v.insert("#anon_quoted-like-args-pattern_0".to_string(), ContextId { index: 4235 });
    v.insert("unqualified-variables".to_string(), ContextId { index: 4383 });
    v.insert("literal-braces-nested".to_string(), ContextId { index: 4315 });
    v.insert("string-format-meta".to_string(), ContextId { index: 4354 });
    v.insert("#anon_string-heredoc-xml_0".to_string(), ContextId { index: 4256 });
    v.insert("literal-parens-nested".to_string(), ContextId { index: 4321 });
    v.insert("#anon_comment-pod-formatting_4".to_string(), ContextId { index: 4201 });
    v.insert("#anon_string-heredoc-css_1".to_string(), ContextId { index: 4247 });
    v.insert("operators".to_string(), ContextId { index: 4326 });
    v.insert("#anon_comment-pod-embedded_3".to_string(), ContextId { index: 4190 });
    v.insert("#anon_comment-pod-formatting_5".to_string(), ContextId { index: 4202 });
    v.insert("#anon_quoted-like-args-substitution_0".to_string(), ContextId { index: 4239 });
    v.insert("#anon_quoted-like-args-pattern_3".to_string(), ContextId { index: 4238 });
    v.insert("literal-generic-pop".to_string(), ContextId { index: 4320 });
    v.insert("#anon_sub-attributes-parameters_0".to_string(), ContextId { index: 4263 });
    v.insert("#anon_comment-pod-embedded_1".to_string(), ContextId { index: 4185 });
    v.insert("#anon_comment-pod-embedded_8".to_string(), ContextId { index: 4195 });
    v.insert("#anon_string-heredoc-javascript_0".to_string(), ContextId { index: 4250 });
    v.insert("#anon_quoted-like-args-pattern_1".to_string(), ContextId { index: 4236 });
    v
  }
} }