
#![allow(unused_imports)]
#![allow(dead_code)]

use jirs_syntect::{*, parsing::*};
use lazycell::AtomicLazyCell;

#[inline(always)]
pub fn load() -> SyntaxReference {
        SyntaxReference {  name: "Python".to_string(),
  file_extensions: vec!["py".to_string(),"py3".to_string(),"pyw".to_string(),"pyi".to_string(),"pyx".to_string(),"pyx.in".to_string(),"pxd".to_string(),"pxd.in".to_string(),"pxi".to_string(),"pxi.in".to_string(),"rpy".to_string(),"cpy".to_string(),"SConstruct".to_string(),"Sconstruct".to_string(),"sconstruct".to_string(),"SConscript".to_string(),"gyp".to_string(),"gypi".to_string(),"Snakefile".to_string(),"vpy".to_string(),"wscript".to_string(),"bazel".to_string(),"bzl".to_string()],
  scope: Scope { a: 844691218104320, b: 0 },
  first_line_match: Some("^#!\\s*/.*\\bpython(\\d(\\.\\d)?)?\\b".to_string()),
  hidden: false,
  variables: {
    let mut v = std::collections::HashMap::new();
    v.insert("simple_expression".to_string(), "(?x:\n  \\s+                      # whitespace\n  | [urfb]*\"(?:\\\\.|[^\"])*\" # strings\n  | [urfb]*\'(?:\\\\.|[^\'])*\' # ^\n  | [\\d.ej]+               # numerics\n  | [+*/%@-] | // | and | or # operators\n  | {{path}}               # a path\n)*".to_string());
    v.insert("format_spec".to_string(), "(?x:\n  (?:.? [<>=^])?     # fill align\n  [ +-]?             # sign\n  \\#?                # alternate form\n  # technically, octal and hexadecimal integers are also supported as \'width\', but rarely used\n  \\d*                # width\n  ,?                 # thousands separator\n  (?:\\.\\d+)?         # precision\n  [bcdeEfFgGnosxX%]? # type\n)".to_string());
    v.insert("identifier".to_string(), "\\b[[:alpha:]_]{{identifier_continue}}*\\b".to_string());
    v.insert("identifier_continue".to_string(), "[[:alnum:]_]".to_string());
    v.insert("illegal_names".to_string(), "(?:and|as|assert|break|class|continue|def|del|elif|else|except|finally|for|from|global|if|import|in|is|lambda|not|or|pass|raise|return|try|while|with|yield)".to_string());
    v.insert("strftime_spec".to_string(), "(?:%(?:[aAwdbBGmyYHIpMSfzZjuUVWcxX%]|-[dmHIMSj]))".to_string());
    v.insert("identifier_constant".to_string(), "\\b(?:[\\p{Lu}_][\\p{Lu}_\\d]*)?[\\p{Lu}]{2,}[\\p{Lu}_\\d]*\\b".to_string());
    v.insert("sql_indicator".to_string(), "\\s*(?:SELECT|INSERT|UPDATE|DELETE|CREATE|REPLACE|ALTER|WITH)\\b".to_string());
    v.insert("exponent".to_string(), "(?:[eE][-+]?{{digits}})".to_string());
    v.insert("digits".to_string(), "(?:\\d+(?:_\\d+)*)".to_string());
    v.insert("path".to_string(), "({{identifier}}[ ]*\\.[ ]*)*{{identifier}}".to_string());
    v
  },
  contexts: {
    let mut v = std::collections::HashMap::new();
    v.insert("#anon_functions_2".to_string(), ContextId { index: 4440 });
    v.insert("dictionaries-and-sets".to_string(), ContextId { index: 4560 });
    v.insert("allow-unpack-operators".to_string(), ContextId { index: 4545 });
    v.insert("inline-for".to_string(), ContextId { index: 4593 });
    v.insert("#anon_string-quoted-single-block_8".to_string(), ContextId { index: 4523 });
    v.insert("#anon_target-list_0".to_string(), ContextId { index: 4541 });
    v.insert("#anon_string-quoted-double-block_8".to_string(), ContextId { index: 4487 });
    v.insert("__start".to_string(), ContextId { index: 4543 });
    v.insert("entity-name-function".to_string(), ContextId { index: 4565 });
    v.insert("#anon_string-quoted-double-block_2".to_string(), ContextId { index: 4481 });
    v.insert("decorators".to_string(), ContextId { index: 4559 });
    v.insert("#anon_string-quoted-single_0".to_string(), ContextId { index: 4525 });
    v.insert("#anon_string-quoted-double_4".to_string(), ContextId { index: 4500 });
    v.insert("#anon_string-quoted-single-block_18".to_string(), ContextId { index: 4516 });
    v.insert("magic-function-names".to_string(), ContextId { index: 4611 });
    v.insert("numbers".to_string(), ContextId { index: 4617 });
    v.insert("with-body".to_string(), ContextId { index: 4630 });
    v.insert("import-alias".to_string(), ContextId { index: 4589 });
    v.insert("#anon_block-statements_5".to_string(), ContextId { index: 4397 });
    v.insert("#anon_docstrings_2".to_string(), ContextId { index: 4414 });
    v.insert("#anon_expression-in-a-group_0".to_string(), ContextId { index: 4416 });
    v.insert("#anon_line-continuation_0".to_string(), ContextId { index: 4462 });
    v.insert("expression-in-a-group".to_string(), ContextId { index: 4570 });
    v.insert("#anon_string-quoted-single-block_14".to_string(), ContextId { index: 4512 });
    v.insert("illegal-assignment-expression".to_string(), ContextId { index: 4586 });
    v.insert("escaped-fstring-escape".to_string(), ContextId { index: 4567 });
    v.insert("#anon_item-access_0".to_string(), ContextId { index: 4455 });
    v.insert("dotted-name-specials".to_string(), ContextId { index: 4563 });
    v.insert("name".to_string(), ContextId { index: 4615 });
    v.insert("#anon_function-parameters_3".to_string(), ContextId { index: 4436 });
    v.insert("inside-dictionary".to_string(), ContextId { index: 4595 });
    v.insert("#anon_dictionaries-and-sets_0".to_string(), ContextId { index: 4411 });
    v.insert("#anon_string-quoted-single-block_13".to_string(), ContextId { index: 4511 });
    v.insert("comments".to_string(), ContextId { index: 4554 });
    v.insert("formatting-syntax".to_string(), ContextId { index: 4577 });
    v.insert("#anon_classes_0".to_string(), ContextId { index: 4399 });
    v.insert("#anon_string-quoted-double-block_18".to_string(), ContextId { index: 4480 });
    v.insert("#anon_string-quoted-single-block_7".to_string(), ContextId { index: 4522 });
    v.insert("#anon_string-quoted-single_11".to_string(), ContextId { index: 4528 });
    v.insert("line-statements".to_string(), ContextId { index: 4609 });
    v.insert("#anon_string-quoted-double_9".to_string(), ContextId { index: 4505 });
    v.insert("#anon_function-call-wrapper_2".to_string(), ContextId { index: 4428 });
    v.insert("#anon_line-statements_1".to_string(), ContextId { index: 4464 });
    v.insert("#anon_string-quoted-double_6".to_string(), ContextId { index: 4502 });
    v.insert("#anon_string-quoted-single_9".to_string(), ContextId { index: 4540 });
    v.insert("assignment-expression".to_string(), ContextId { index: 4547 });
    v.insert("constant-placeholder".to_string(), ContextId { index: 4555 });
    v.insert("#anon_string-quoted-single_1".to_string(), ContextId { index: 4526 });
    v.insert("#anon_string-quoted-single_6".to_string(), ContextId { index: 4537 });
    v.insert("#anon_string-quoted-single_13".to_string(), ContextId { index: 4530 });
    v.insert("#anon_inside-directory-value_1".to_string(), ContextId { index: 4452 });
    v.insert("inside-directory-value".to_string(), ContextId { index: 4596 });
    v.insert("#anon_decorator-wrapper_0".to_string(), ContextId { index: 4408 });
    v.insert("inside-tuple".to_string(), ContextId { index: 4599 });
    v.insert("decorator-function-call-wrapper".to_string(), ContextId { index: 4557 });
    v.insert("tuples".to_string(), ContextId { index: 4628 });
    v.insert("decorator-wrapper".to_string(), ContextId { index: 4558 });
    v.insert("#anon_string-quoted-single-block_12".to_string(), ContextId { index: 4510 });
    v.insert("#anon_string-quoted-double-block_10".to_string(), ContextId { index: 4472 });
    v.insert("#anon_string-quoted-double_2".to_string(), ContextId { index: 4498 });
    v.insert("line-continuation".to_string(), ContextId { index: 4605 });
    v.insert("#anon_string-quoted-single_15".to_string(), ContextId { index: 4532 });
    v.insert("#anon_keyword-arguments_1".to_string(), ContextId { index: 4459 });
    v.insert("#anon_block-statements_4".to_string(), ContextId { index: 4396 });
    v.insert("imports".to_string(), ContextId { index: 4592 });
    v.insert("#anon_imports_4".to_string(), ContextId { index: 4447 });
    v.insert("#anon_string-quoted-single-block_2".to_string(), ContextId { index: 4517 });
    v.insert("#anon_string-quoted-single_14".to_string(), ContextId { index: 4531 });
    v.insert("#anon_string-quoted-double-block_6".to_string(), ContextId { index: 4485 });
    v.insert("#anon_string-quoted-single_3".to_string(), ContextId { index: 4534 });
    v.insert("#anon_string-quoted-single-block_0".to_string(), ContextId { index: 4506 });
    v.insert("#anon_string-quoted-double_15".to_string(), ContextId { index: 4496 });
    v.insert("#anon_modifiers_0".to_string(), ContextId { index: 4465 });
    v.insert("#anon_f-string-replacement_0".to_string(), ContextId { index: 4420 });
    v.insert("#anon_string-quoted-single-block_15".to_string(), ContextId { index: 4513 });
    v.insert("arguments".to_string(), ContextId { index: 4546 });
    v.insert("#anon_function-call-wrapper_0".to_string(), ContextId { index: 4426 });
    v.insert("#anon_string-quoted-single-block_1".to_string(), ContextId { index: 4507 });
    v.insert("escaped-unicode-char".to_string(), ContextId { index: 4568 });
    v.insert("#anon_qualified-name_0".to_string(), ContextId { index: 4469 });
    v.insert("#anon_classes_4".to_string(), ContextId { index: 4403 });
    v.insert("#anon_function-call-wrapper_3".to_string(), ContextId { index: 4429 });
    v.insert("block-statements".to_string(), ContextId { index: 4549 });
    v.insert("#anon_decorator-function-call-wrapper_0".to_string(), ContextId { index: 4405 });
    v.insert("inside-set".to_string(), ContextId { index: 4598 });
    v.insert("strings".to_string(), ContextId { index: 4626 });
    v.insert("inline-if".to_string(), ContextId { index: 4594 });
    v.insert("#anon_line-statements_0".to_string(), ContextId { index: 4463 });
    v.insert("#anon_function-call-wrapper_1".to_string(), ContextId { index: 4427 });
    v.insert("modifiers".to_string(), ContextId { index: 4614 });
    v.insert("#anon_name_0".to_string(), ContextId { index: 4466 });
    v.insert("#anon_string-quoted-single-block_11".to_string(), ContextId { index: 4509 });
    v.insert("#anon_qualified-name-until-leaf_0".to_string(), ContextId { index: 4467 });
    v.insert("escaped-char".to_string(), ContextId { index: 4566 });
    v.insert("f-string-content".to_string(), ContextId { index: 4573 });
    v.insert("keyword-arguments".to_string(), ContextId { index: 4601 });
    v.insert("#anon_string-quoted-double-block_13".to_string(), ContextId { index: 4475 });
    v.insert("docstrings".to_string(), ContextId { index: 4561 });
    v.insert("#anon_after-expression_2".to_string(), ContextId { index: 4391 });
    v.insert("#anon_groups_0".to_string(), ContextId { index: 4441 });
    v.insert("#anon_imports_2".to_string(), ContextId { index: 4445 });
    v.insert("#anon_string-quoted-double-block_11".to_string(), ContextId { index: 4473 });
    v.insert("#anon_string-quoted-single-block_6".to_string(), ContextId { index: 4521 });
    v.insert("functions".to_string(), ContextId { index: 4583 });
    v.insert("inside-list".to_string(), ContextId { index: 4597 });
    v.insert("after-expression".to_string(), ContextId { index: 4544 });
    v.insert("#anon_inside-dictionary_0".to_string(), ContextId { index: 4449 });
    v.insert("#anon_string-quoted-double_5".to_string(), ContextId { index: 4501 });
    v.insert("#anon_qualified-name-until-leaf_1".to_string(), ContextId { index: 4468 });
    v.insert("#anon_string-quoted-single_8".to_string(), ContextId { index: 4539 });
    v.insert("#anon_imports_3".to_string(), ContextId { index: 4446 });
    v.insert("#anon_string-quoted-single-block_9".to_string(), ContextId { index: 4524 });
    v.insert("#anon_string-quoted-double-block_3".to_string(), ContextId { index: 4482 });
    v.insert("#anon_import-from-name_0".to_string(), ContextId { index: 4442 });
    v.insert("#anon_string-quoted-double_3".to_string(), ContextId { index: 4499 });
    v.insert("#anon_string-quoted-single-block_16".to_string(), ContextId { index: 4514 });
    v.insert("function-calls".to_string(), ContextId { index: 4580 });
    v.insert("#anon_string-quoted-double-block_12".to_string(), ContextId { index: 4474 });
    v.insert("#anon_decorators_0".to_string(), ContextId { index: 4410 });
    v.insert("function-call-wrapper".to_string(), ContextId { index: 4579 });
    v.insert("string-quoted-single-block".to_string(), ContextId { index: 4625 });
    v.insert("#anon_block-statements_3".to_string(), ContextId { index: 4395 });
    v.insert("#anon_classes_1".to_string(), ContextId { index: 4400 });
    v.insert("#anon_string-quoted-single-block_10".to_string(), ContextId { index: 4508 });
    v.insert("#anon_decorator-function-call-wrapper_2".to_string(), ContextId { index: 4407 });
    v.insert("#anon_function-parameters_0".to_string(), ContextId { index: 4433 });
    v.insert("#anon_f-string-replacement-reset_1".to_string(), ContextId { index: 4418 });
    v.insert("#anon_block-statements_2".to_string(), ContextId { index: 4394 });
    v.insert("#anon_string-quoted-double_8".to_string(), ContextId { index: 4504 });
    v.insert("#anon_string-quoted-double_12".to_string(), ContextId { index: 4493 });
    v.insert("#anon_functions_0".to_string(), ContextId { index: 4438 });
    v.insert("#anon_block-statements_0".to_string(), ContextId { index: 4392 });
    v.insert("lambda".to_string(), ContextId { index: 4602 });
    v.insert("line-continuation-inside-string".to_string(), ContextId { index: 4607 });
    v.insert("#anon_string-quoted-double_1".to_string(), ContextId { index: 4490 });
    v.insert("#anon_string-quoted-double-block_17".to_string(), ContextId { index: 4479 });
    v.insert("__main".to_string(), ContextId { index: 4542 });
    v.insert("statements".to_string(), ContextId { index: 4621 });
    v.insert("#anon_function-parameters-tuple_2".to_string(), ContextId { index: 4432 });
    v.insert("#anon_string-quoted-double-block_0".to_string(), ContextId { index: 4470 });
    v.insert("#anon_keyword-arguments_0".to_string(), ContextId { index: 4458 });
    v.insert("item-access".to_string(), ContextId { index: 4600 });
    v.insert("#anon_after-expression_1".to_string(), ContextId { index: 4390 });
    v.insert("#anon_string-quoted-single-block_17".to_string(), ContextId { index: 4515 });
    v.insert("#anon_string-quoted-double_16".to_string(), ContextId { index: 4497 });
    v.insert("#anon_string-quoted-single_7".to_string(), ContextId { index: 4538 });
    v.insert("#anon_dotted-name_0".to_string(), ContextId { index: 4415 });
    v.insert("#anon_docstrings_1".to_string(), ContextId { index: 4413 });
    v.insert("#anon_f-string-replacement_2".to_string(), ContextId { index: 4422 });
    v.insert("dotted-name".to_string(), ContextId { index: 4562 });
    v.insert("#anon_lambda-parameters_1".to_string(), ContextId { index: 4461 });
    v.insert("function-after-parameters".to_string(), ContextId { index: 4578 });
    v.insert("#anon_string-quoted-single-block_3".to_string(), ContextId { index: 4518 });
    v.insert("assignments".to_string(), ContextId { index: 4548 });
    v.insert("line-continuation-inside-block-string".to_string(), ContextId { index: 4606 });
    v.insert("qualified-name-until-leaf".to_string(), ContextId { index: 4620 });
    v.insert("#anon_string-quoted-double-block_9".to_string(), ContextId { index: 4488 });
    v.insert("#anon_function-after-parameters_0".to_string(), ContextId { index: 4425 });
    v.insert("#anon_comments_0".to_string(), ContextId { index: 4404 });
    v.insert("groups".to_string(), ContextId { index: 4585 });
    v.insert("#anon_string-quoted-double-block_5".to_string(), ContextId { index: 4484 });
    v.insert("illegal-names".to_string(), ContextId { index: 4587 });
    v.insert("#anon_lambda-parameters_0".to_string(), ContextId { index: 4460 });
    v.insert("#anon_f-string-replacement_1".to_string(), ContextId { index: 4421 });
    v.insert("#anon_string-quoted-double_10".to_string(), ContextId { index: 4491 });
    v.insert("#anon_function-parameters_4".to_string(), ContextId { index: 4437 });
    v.insert("#anon_inline-for_0".to_string(), ContextId { index: 4448 });
    v.insert("#anon_string-quoted-single_5".to_string(), ContextId { index: 4536 });
    v.insert("builtin-types".to_string(), ContextId { index: 4552 });
    v.insert("#anon_formatting-syntax_0".to_string(), ContextId { index: 4423 });
    v.insert("#anon_string-quoted-single_4".to_string(), ContextId { index: 4535 });
    v.insert("#anon_imports_0".to_string(), ContextId { index: 4443 });
    v.insert("expressions-common".to_string(), ContextId { index: 4572 });
    v.insert("#anon_item-access_2".to_string(), ContextId { index: 4457 });
    v.insert("function-parameters".to_string(), ContextId { index: 4581 });
    v.insert("yields".to_string(), ContextId { index: 4631 });
    v.insert("#anon_function-parameters-tuple_0".to_string(), ContextId { index: 4430 });
    v.insert("expression-as-a-statement".to_string(), ContextId { index: 4569 });
    v.insert("#anon_string-quoted-single_10".to_string(), ContextId { index: 4527 });
    v.insert("#anon_classes_3".to_string(), ContextId { index: 4402 });
    v.insert("#anon_string-quoted-double-block_1".to_string(), ContextId { index: 4471 });
    v.insert("#anon_function-parameters-tuple_1".to_string(), ContextId { index: 4431 });
    v.insert("#anon_inside-set_0".to_string(), ContextId { index: 4454 });
    v.insert("#anon_string-quoted-single-block_5".to_string(), ContextId { index: 4520 });
    v.insert("#anon_function-parameters_1".to_string(), ContextId { index: 4434 });
    v.insert("line-continuation-or-pop".to_string(), ContextId { index: 4608 });
    v.insert("illegal-names-pop".to_string(), ContextId { index: 4588 });
    v.insert("#anon_decorator-function-call-wrapper_1".to_string(), ContextId { index: 4406 });
    v.insert("#anon_string-quoted-double_14".to_string(), ContextId { index: 4495 });
    v.insert("f-string-replacement-reset".to_string(), ContextId { index: 4576 });
    v.insert("with-as".to_string(), ContextId { index: 4629 });
    v.insert("#anon_imports_1".to_string(), ContextId { index: 4444 });
    v.insert("name-specials".to_string(), ContextId { index: 4616 });
    v.insert("#anon_docstrings_0".to_string(), ContextId { index: 4412 });
    v.insert("classes".to_string(), ContextId { index: 4553 });
    v.insert("#anon_inside-directory-value_0".to_string(), ContextId { index: 4451 });
    v.insert("#anon_string-quoted-double-block_15".to_string(), ContextId { index: 4477 });
    v.insert("#anon_inside-dictionary_1".to_string(), ContextId { index: 4450 });
    v.insert("#anon_item-access_1".to_string(), ContextId { index: 4456 });
    v.insert("expression-in-a-statement".to_string(), ContextId { index: 4571 });
    v.insert("f-string-replacement".to_string(), ContextId { index: 4575 });
    v.insert("#anon_block-statements_1".to_string(), ContextId { index: 4393 });
    v.insert("#anon_formatting-syntax_1".to_string(), ContextId { index: 4424 });
    v.insert("#anon_string-quoted-double-block_16".to_string(), ContextId { index: 4478 });
    v.insert("function-parameters-tuple".to_string(), ContextId { index: 4582 });
    v.insert("lists".to_string(), ContextId { index: 4610 });
    v.insert("operators".to_string(), ContextId { index: 4618 });
    v.insert("string-quoted-double".to_string(), ContextId { index: 4622 });
    v.insert("#anon_after-expression_0".to_string(), ContextId { index: 4389 });
    v.insert("magic-variable-names".to_string(), ContextId { index: 4612 });
    v.insert("lambda-parameters".to_string(), ContextId { index: 4603 });
    v.insert("constants".to_string(), ContextId { index: 4556 });
    v.insert("string-quoted-single".to_string(), ContextId { index: 4624 });
    v.insert("target-list".to_string(), ContextId { index: 4627 });
    v.insert("#anon_inside-directory-value_2".to_string(), ContextId { index: 4453 });
    v.insert("language-variables".to_string(), ContextId { index: 4604 });
    v.insert("#anon_f-string-replacement-reset_0".to_string(), ContextId { index: 4417 });
    v.insert("#anon_string-quoted-double_11".to_string(), ContextId { index: 4492 });
    v.insert("#anon_block-statements_6".to_string(), ContextId { index: 4398 });
    v.insert("#anon_string-quoted-single-block_4".to_string(), ContextId { index: 4519 });
    v.insert("#anon_functions_1".to_string(), ContextId { index: 4439 });
    v.insert("#anon_string-quoted-double-block_4".to_string(), ContextId { index: 4483 });
    v.insert("#anon_string-quoted-double-block_7".to_string(), ContextId { index: 4486 });
    v.insert("#anon_string-quoted-single_12".to_string(), ContextId { index: 4529 });
    v.insert("#anon_string-quoted-double-block_14".to_string(), ContextId { index: 4476 });
    v.insert("entity-name-class".to_string(), ContextId { index: 4564 });
    v.insert("string-quoted-double-block".to_string(), ContextId { index: 4623 });
    v.insert("#anon_string-quoted-double_7".to_string(), ContextId { index: 4503 });
    v.insert("import-name-list".to_string(), ContextId { index: 4591 });
    v.insert("qualified-name".to_string(), ContextId { index: 4619 });
    v.insert("builtin-exceptions".to_string(), ContextId { index: 4550 });
    v.insert("builtin-functions".to_string(), ContextId { index: 4551 });
    v.insert("f-string-content-with-regex".to_string(), ContextId { index: 4574 });
    v.insert("#anon_string-quoted-double_0".to_string(), ContextId { index: 4489 });
    v.insert("#anon_decorator-wrapper_1".to_string(), ContextId { index: 4409 });
    v.insert("main".to_string(), ContextId { index: 4613 });
    v.insert("#anon_string-quoted-double_13".to_string(), ContextId { index: 4494 });
    v.insert("#anon_f-string-replacement-reset_2".to_string(), ContextId { index: 4419 });
    v.insert("import-from-name".to_string(), ContextId { index: 4590 });
    v.insert("#anon_classes_2".to_string(), ContextId { index: 4401 });
    v.insert("generic-names".to_string(), ContextId { index: 4584 });
    v.insert("#anon_function-parameters_2".to_string(), ContextId { index: 4435 });
    v.insert("#anon_string-quoted-single_2".to_string(), ContextId { index: 4533 });
    v
  }
} }