
#![allow(unused_imports)]
#![allow(dead_code)]

use jirs_syntect::{*, parsing::*};
use lazycell::AtomicLazyCell;

#[inline(always)]
pub fn load() -> SyntaxReference {
        SyntaxReference {  name: "Ruby".to_string(),
  file_extensions: vec!["rb".to_string(),"Appfile".to_string(),"Appraisals".to_string(),"Berksfile".to_string(),"Brewfile".to_string(),"capfile".to_string(),"cgi".to_string(),"Cheffile".to_string(),"config.ru".to_string(),"Deliverfile".to_string(),"Fastfile".to_string(),"fcgi".to_string(),"Gemfile".to_string(),"gemspec".to_string(),"Guardfile".to_string(),"irbrc".to_string(),"jbuilder".to_string(),"Podfile".to_string(),"podspec".to_string(),"prawn".to_string(),"rabl".to_string(),"rake".to_string(),"Rakefile".to_string(),"Rantfile".to_string(),"rbx".to_string(),"rjs".to_string(),"ruby.rail".to_string(),"Scanfile".to_string(),"simplecov".to_string(),"Snapfile".to_string(),"thor".to_string(),"Thorfile".to_string(),"Vagrantfile".to_string()],
  scope: Scope { a: 844708397973504, b: 0 },
  first_line_match: Some("(?xi:\n  ^\\#! .* \\bj?ruby\\b |                # shebang\n  ^\\# \\s* -\\*- [^*]* ruby [^*]* -\\*-  # editorconfig\n)".to_string()),
  hidden: false,
  variables: {
    let mut v = std::collections::HashMap::new();
    v.insert("odigits".to_string(), "(?:[0-7]+(?:_[0-7]+)*)".to_string());
    v.insert("method_name".to_string(), "{{identifier}}{{method_punctuation}}".to_string());
    v.insert("bdigits".to_string(), "(?:[01]+(?:_[01]+)*)".to_string());
    v.insert("heredoc_type_html".to_string(), "(?:[[:upper:]_]_)?HTML".to_string());
    v.insert("heredoc_type_sql".to_string(), "(?:[[:upper:]_]_)?SQL".to_string());
    v.insert("path_lookahead".to_string(), "(::)?({{identifier}}(\\.|::))*{{identifier}}".to_string());
    v.insert("heredoc_type_css".to_string(), "(?:[[:upper:]_]_)?CSS".to_string());
    v.insert("hdigits".to_string(), "(?:\\h+(?:_\\h+)*)".to_string());
    v.insert("heredoc_type_shell".to_string(), "(?:[[:upper:]_]_)?(?:SH|SHELL)".to_string());
    v.insert("ddigits".to_string(), "(?:\\d+(?:_\\d+)*)".to_string());
    v.insert("heredoc_type_ruby".to_string(), "(?:[[:upper:]_]_)?RUBY".to_string());
    v.insert("method_punctuation".to_string(), "(?:[?!]|=(?![>=]))?".to_string());
    v.insert("heredoc_type_js".to_string(), "(?:[[:upper:]_]_)?(?:JS|JAVASCRIPT)".to_string());
    v.insert("exponent".to_string(), "(?:[Ee][-+]?{{ddigits}})".to_string());
    v.insert("identifier".to_string(), "\\b[[:alpha:]_][[:alnum:]_]*\\b".to_string());
    v
  },
  contexts: {
    let mut v = std::collections::HashMap::new();
    v.insert("#anon_identifiers-accessors_1".to_string(), ContextId { index: 4806 });
    v.insert("#anon_nest-ltgt_0".to_string(), ContextId { index: 4842 });
    v.insert("indented-heredoc-end".to_string(), ContextId { index: 4912 });
    v.insert("#anon_early-strings_7".to_string(), ContextId { index: 4803 });
    v.insert("heredoc-sql-indented-interpolated".to_string(), ContextId { index: 4906 });
    v.insert("heredoc-html-indented-interpolated".to_string(), ContextId { index: 4881 });
    v.insert("#anon_escaped-char_0".to_string(), ContextId { index: 4804 });
    v.insert("#anon_method_0".to_string(), ContextId { index: 4832 });
    v.insert("#anon_nest-parens-i_0".to_string(), ContextId { index: 4843 });
    v.insert("after-keyword".to_string(), ContextId { index: 4860 });
    v.insert("nest-parens-i".to_string(), ContextId { index: 4945 });
    v.insert("nest-brackets-i".to_string(), ContextId { index: 4932 });
    v.insert("operators".to_string(), ContextId { index: 4947 });
    v.insert("punctuation".to_string(), ContextId { index: 4948 });
    v.insert("#anon_constants_0".to_string(), ContextId { index: 4791 });
    v.insert("#anon_method-parameters_4".to_string(), ContextId { index: 4831 });
    v.insert("method-parameters".to_string(), ContextId { index: 4924 });
    v.insert("#anon_regexes_3".to_string(), ContextId { index: 4852 });
    v.insert("interpolated-ruby-expressions".to_string(), ContextId { index: 4915 });
    v.insert("#anon_constants_2".to_string(), ContextId { index: 4793 });
    v.insert("#anon_early-strings_6".to_string(), ContextId { index: 4802 });
    v.insert("method-parameters-start".to_string(), ContextId { index: 4925 });
    v.insert("well-known-methods".to_string(), ContextId { index: 4958 });
    v.insert("heredoc-ruby-unindented-interpolated".to_string(), ContextId { index: 4898 });
    v.insert("constants".to_string(), ContextId { index: 4869 });
    v.insert("#anon_class-inheritance_0".to_string(), ContextId { index: 4787 });
    v.insert("heredoc-html".to_string(), ContextId { index: 4880 });
    v.insert("trailing-heredoc-start".to_string(), ContextId { index: 4954 });
    v.insert("#anon_comments_1".to_string(), ContextId { index: 4790 });
    v.insert("heredoc-js".to_string(), ContextId { index: 4885 });
    v.insert("heredoc-shell-indented-literal".to_string(), ContextId { index: 4902 });
    v.insert("#anon_method-parameters_2".to_string(), ContextId { index: 4829 });
    v.insert("#anon_try-regex_0".to_string(), ContextId { index: 4854 });
    v.insert("class-declaration".to_string(), ContextId { index: 4865 });
    v.insert("heredoc-sql-unindented-literal".to_string(), ContextId { index: 4909 });
    v.insert("#anon_early-strings_1".to_string(), ContextId { index: 4797 });
    v.insert("#anon_late-strings_0".to_string(), ContextId { index: 4811 });
    v.insert("#anon_early-strings_3".to_string(), ContextId { index: 4799 });
    v.insert("heredoc-html-unindented-literal".to_string(), ContextId { index: 4884 });
    v.insert("#anon_late-strings_3".to_string(), ContextId { index: 4815 });
    v.insert("identifiers-accessors".to_string(), ContextId { index: 4911 });
    v.insert("nest-brackets-r".to_string(), ContextId { index: 4933 });
    v.insert("nest-ltgt-i".to_string(), ContextId { index: 4942 });
    v.insert("#anon_early-strings_4".to_string(), ContextId { index: 4800 });
    v.insert("#anon_nest-curly-r_0".to_string(), ContextId { index: 4839 });
    v.insert("#anon_early-strings_2".to_string(), ContextId { index: 4798 });
    v.insert("#anon_nest-all_1".to_string(), ContextId { index: 4835 });
    v.insert("#anon_method-parameters-start_0".to_string(), ContextId { index: 4826 });
    v.insert("#anon_nest-ltgt-r_0".to_string(), ContextId { index: 4841 });
    v.insert("blocks".to_string(), ContextId { index: 4863 });
    v.insert("heredoc-plain-unindented-literal".to_string(), ContextId { index: 4894 });
    v.insert("heredoc-ruby-unindented-literal".to_string(), ContextId { index: 4899 });
    v.insert("__main".to_string(), ContextId { index: 4857 });
    v.insert("#anon_late-strings_2".to_string(), ContextId { index: 4814 });
    v.insert("#anon_nest-all_0".to_string(), ContextId { index: 4834 });
    v.insert("heredoc-plain".to_string(), ContextId { index: 4890 });
    v.insert("heredoc-shell-unindented-literal".to_string(), ContextId { index: 4904 });
    v.insert("heredocs".to_string(), ContextId { index: 4910 });
    v.insert("module-declaration".to_string(), ContextId { index: 4927 });
    v.insert("#anon_method-bare-parameters_3".to_string(), ContextId { index: 4825 });
    v.insert("nest-curly".to_string(), ContextId { index: 4934 });
    v.insert("#anon_class-inheritance_1".to_string(), ContextId { index: 4788 });
    v.insert("#anon_late-strings_8".to_string(), ContextId { index: 4820 });
    v.insert("#anon_late-strings_6".to_string(), ContextId { index: 4818 });
    v.insert("#anon_interpolated-ruby_0".to_string(), ContextId { index: 4809 });
    v.insert("#anon_method-parameters_1".to_string(), ContextId { index: 4828 });
    v.insert("#anon_regexes_4".to_string(), ContextId { index: 4853 });
    v.insert("#anon_method-parameters_0".to_string(), ContextId { index: 4827 });
    v.insert("#anon_method-bare-parameters_0".to_string(), ContextId { index: 4822 });
    v.insert("#anon_block-parameters_1".to_string(), ContextId { index: 4786 });
    v.insert("#anon_module-declaration_0".to_string(), ContextId { index: 4833 });
    v.insert("#anon_nest-brackets-i_0".to_string(), ContextId { index: 4836 });
    v.insert("heredoc-js-indented-literal".to_string(), ContextId { index: 4887 });
    v.insert("heredoc-shell-indented-interpolated".to_string(), ContextId { index: 4901 });
    v.insert("name-parts".to_string(), ContextId { index: 4928 });
    v.insert("nest-parens".to_string(), ContextId { index: 4944 });
    v.insert("trailing-heredoc".to_string(), ContextId { index: 4953 });
    v.insert("#anon_nest-ltgt-i_0".to_string(), ContextId { index: 4840 });
    v.insert("#anon_late-strings_5".to_string(), ContextId { index: 4817 });
    v.insert("heredoc-plain-indented-literal".to_string(), ContextId { index: 4892 });
    v.insert("#anon_early-strings_0".to_string(), ContextId { index: 4796 });
    v.insert("#anon_block-parameters_0".to_string(), ContextId { index: 4785 });
    v.insert("class".to_string(), ContextId { index: 4864 });
    v.insert("nest-all-inner".to_string(), ContextId { index: 4930 });
    v.insert("try-regex".to_string(), ContextId { index: 4955 });
    v.insert("#anon_data-section_0".to_string(), ContextId { index: 4794 });
    v.insert("#anon_late-strings_4".to_string(), ContextId { index: 4816 });
    v.insert("#anon_nest-brackets-r_0".to_string(), ContextId { index: 4837 });
    v.insert("#anon_late-strings_9".to_string(), ContextId { index: 4821 });
    v.insert("heredoc-css-unindented-interpolated".to_string(), ContextId { index: 4878 });
    v.insert("#anon_regexes_2".to_string(), ContextId { index: 4851 });
    v.insert("heredoc-js-indented-interpolated".to_string(), ContextId { index: 4886 });
    v.insert("block-parameters".to_string(), ContextId { index: 4862 });
    v.insert("class-inheritance".to_string(), ContextId { index: 4866 });
    v.insert("heredoc-html-unindented-interpolated".to_string(), ContextId { index: 4883 });
    v.insert("#anon_regex-sub_0".to_string(), ContextId { index: 4847 });
    v.insert("#anon_early-strings_5".to_string(), ContextId { index: 4801 });
    v.insert("nest-ltgt-r".to_string(), ContextId { index: 4943 });
    v.insert("#anon_late-strings_7".to_string(), ContextId { index: 4819 });
    v.insert("#anon_interpolated-heredoc-ruby_0".to_string(), ContextId { index: 4807 });
    v.insert("main".to_string(), ContextId { index: 4920 });
    v.insert("method".to_string(), ContextId { index: 4922 });
    v.insert("after-operator".to_string(), ContextId { index: 4861 });
    v.insert("class-name".to_string(), ContextId { index: 4867 });
    v.insert("nest-curly-i-inner".to_string(), ContextId { index: 4938 });
    v.insert("#anon_interpolated-ruby_1".to_string(), ContextId { index: 4810 });
    v.insert("#anon_method-bare-parameters_1".to_string(), ContextId { index: 4823 });
    v.insert("#anon_operators_0".to_string(), ContextId { index: 4846 });
    v.insert("strings".to_string(), ContextId { index: 4952 });
    v.insert("heredoc-sql-unindented-interpolated".to_string(), ContextId { index: 4908 });
    v.insert("regexes".to_string(), ContextId { index: 4950 });
    v.insert("heredoc-plain-indented-interpolated".to_string(), ContextId { index: 4891 });
    v.insert("nest-ltgt".to_string(), ContextId { index: 4941 });
    v.insert("heredoc-shell-unindented-interpolated".to_string(), ContextId { index: 4903 });
    v.insert("comments".to_string(), ContextId { index: 4868 });
    v.insert("interpolated-ruby".to_string(), ContextId { index: 4914 });
    v.insert("#anon_well-known-methods_0".to_string(), ContextId { index: 4856 });
    v.insert("heredoc-css".to_string(), ContextId { index: 4875 });
    v.insert("nest-curly-inner".to_string(), ContextId { index: 4939 });
    v.insert("heredoc-ruby-indented-literal".to_string(), ContextId { index: 4897 });
    v.insert("invalid".to_string(), ContextId { index: 4917 });
    v.insert("expressions".to_string(), ContextId { index: 4873 });
    v.insert("heredoc-html-indented-literal".to_string(), ContextId { index: 4882 });
    v.insert("unindented-heredoc-end".to_string(), ContextId { index: 4956 });
    v.insert("heredoc-js-unindented-literal".to_string(), ContextId { index: 4889 });
    v.insert("string-placeholder".to_string(), ContextId { index: 4951 });
    v.insert("#anon_identifiers-accessors_0".to_string(), ContextId { index: 4805 });
    v.insert("#anon_nest-brackets_0".to_string(), ContextId { index: 4838 });
    v.insert("early-strings".to_string(), ContextId { index: 4871 });
    v.insert("nest-curly-r".to_string(), ContextId { index: 4940 });
    v.insert("#anon_constants_1".to_string(), ContextId { index: 4792 });
    v.insert("data-section".to_string(), ContextId { index: 4870 });
    v.insert("heredoc-css-indented-interpolated".to_string(), ContextId { index: 4876 });
    v.insert("nest-curly-i".to_string(), ContextId { index: 4937 });
    v.insert("#anon_late-strings_1".to_string(), ContextId { index: 4812 });
    v.insert("heredoc-shell".to_string(), ContextId { index: 4900 });
    v.insert("maybe-block-parameters".to_string(), ContextId { index: 4921 });
    v.insert("#anon_regexes_0".to_string(), ContextId { index: 4849 });
    v.insert("#anon_comments_0".to_string(), ContextId { index: 4789 });
    v.insert("heredoc-plain-unindented-interpolated".to_string(), ContextId { index: 4893 });
    v.insert("escaped-char".to_string(), ContextId { index: 4872 });
    v.insert("#anon_data-section_1".to_string(), ContextId { index: 4795 });
    v.insert("method-bare-parameters".to_string(), ContextId { index: 4923 });
    v.insert("heredoc-css-indented-literal".to_string(), ContextId { index: 4877 });
    v.insert("#anon_interpolated-heredoc-ruby_1".to_string(), ContextId { index: 4808 });
    v.insert("#anon_method-bare-parameters_2".to_string(), ContextId { index: 4824 });
    v.insert("#anon_regex-sub_1".to_string(), ContextId { index: 4848 });
    v.insert("heredoc-ruby-indented-interpolated".to_string(), ContextId { index: 4896 });
    v.insert("keywords".to_string(), ContextId { index: 4918 });
    v.insert("nest-curly-expressions".to_string(), ContextId { index: 4935 });
    v.insert("nest-curly-expressions-inner".to_string(), ContextId { index: 4936 });
    v.insert("#anon_variables_0".to_string(), ContextId { index: 4855 });
    v.insert("heredoc-sql-indented-literal".to_string(), ContextId { index: 4907 });
    v.insert("heredoc-ruby".to_string(), ContextId { index: 4895 });
    v.insert("#anon_late-strings_10".to_string(), ContextId { index: 4813 });
    v.insert("module".to_string(), ContextId { index: 4926 });
    v.insert("regex-sub".to_string(), ContextId { index: 4949 });
    v.insert("#anon_nest-parens-r_0".to_string(), ContextId { index: 4844 });
    v.insert("#anon_nest-parens_0".to_string(), ContextId { index: 4845 });
    v.insert("__start".to_string(), ContextId { index: 4858 });
    v.insert("nest-all".to_string(), ContextId { index: 4929 });
    v.insert("nest-parens-r".to_string(), ContextId { index: 4946 });
    v.insert("late-strings".to_string(), ContextId { index: 4919 });
    v.insert("interpolated-ruby-variables".to_string(), ContextId { index: 4916 });
    v.insert("nest-brackets".to_string(), ContextId { index: 4931 });
    v.insert("variables".to_string(), ContextId { index: 4957 });
    v.insert("heredoc-css-unindented-literal".to_string(), ContextId { index: 4879 });
    v.insert("heredoc-sql".to_string(), ContextId { index: 4905 });
    v.insert("interpolated-heredoc-ruby".to_string(), ContextId { index: 4913 });
    v.insert("#anon_method-parameters_3".to_string(), ContextId { index: 4830 });
    v.insert("#anon_regexes_1".to_string(), ContextId { index: 4850 });
    v.insert("after-identifier".to_string(), ContextId { index: 4859 });
    v.insert("function-call-arguments".to_string(), ContextId { index: 4874 });
    v.insert("heredoc-js-unindented-interpolated".to_string(), ContextId { index: 4888 });
    v
  }
} }