DROP TYPE IF EXISTS ProjectCategory CASCADE;

DROP TABLE IF EXISTS projects CASCADE;

DROP TABLE IF EXISTS users CASCADE;

DROP TABLE IF EXISTS issues CASCADE;

DROP TABLE IF EXISTS comments CASCADE;

DROP TABLE IF EXISTS tokens CASCADE;

DROP EXTENSION IF EXISTS "uuid-ossp";

