DROP TYPE IF EXISTS "ProjectCategoryType" CASCADE;
DROP TYPE IF EXISTS "IssuePriorityType" CASCADE;
DROP TYPE IF EXISTS "IssueTypeType" CASCADE;

DROP TABLE IF EXISTS projects CASCADE;

DROP TABLE IF EXISTS users CASCADE;

DROP TABLE IF EXISTS issues CASCADE;

DROP TABLE IF EXISTS comments CASCADE;

DROP TABLE IF EXISTS tokens CASCADE;

DROP EXTENSION IF EXISTS "uuid-ossp";

